# Generated by Django 2.1 on 2020-03-22 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_number', models.IntegerField(blank=True, null=True, verbose_name='ABF Number')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Balance')),
                ('last_top_up_date', models.DateTimeField(auto_now_add=True, verbose_name='Last Top Up Date')),
                ('last_top_up_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Last Top Up Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('IN', 'Intent'), ('OK', 'Received'), ('CA', 'Cancelled')], default='IN', max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
