# Generated by Django 2.1 on 2020-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('ST', 'Started - payment identified'), ('IN', 'Intent - received intent from Stripe'), ('OK', 'Okay - payment completed successfully'), ('CA', 'Cancelled - payment cancelled'), ('FA', 'Failed - payment failed')], default='IN', max_length=2),
        ),
    ]
