# Generated by Django 2.1.5 on 2020-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200324_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='route_code',
            field=models.CharField(max_length=4, null=True, verbose_name='Internal routing code for callback'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='route_payload',
            field=models.CharField(max_length=40, null=True, verbose_name='Payload to return to callback'),
        ),
    ]
