# Generated by Django 2.1.5 on 2020-03-25 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_auto_20200325_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance after transaction')),
                ('description', models.CharField(max_length=80, null=True, verbose_name='Transaction description')),
                ('counterparty', models.CharField(max_length=80, null=True, verbose_name='Counterparty')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Started - payment needs made'), ('Intent', 'Intent - received customer intent to pay from Stripe'), ('Complete', 'Success - payment completed successfully'), ('Failed', 'Failed - payment failed')], default='Initiated', max_length=9, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='account',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Transaction'),
        ),
    ]
