# Generated by Django 2.1.5 on 2020-03-26 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20200325_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='system_number',
        ),
        migrations.AddField(
            model_name='balance',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
