# Generated by Django 2.1 on 2020-04-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20200326_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reference_no',
            field=models.CharField(default='8541-8541-8541', max_length=14, verbose_name='Reference No'),
        ),
    ]
