# Generated by Django 2.1 on 2020-04-17 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_auto_20200416_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_amount', models.IntegerField(verbose_name='Auto Top Up Amount')),
                ('stripe_customer_id', models.CharField(max_length=25, null=True, verbose_name='Stripe Customer Id')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='reference_no',
            field=models.CharField(max_length=14, verbose_name='Reference No'),
        ),
    ]
