# Generated by Django 2.1 on 2020-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20200417_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotopup',
            name='auto_amount',
            field=models.IntegerField(null=True, verbose_name='Auto Top Up Amount'),
        ),
    ]
