# Generated by Django 2.1 on 2020-04-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20200417_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Transfer Out', 'Money transfered out of account'), ('Transfer In', 'Money transfered in to account'), ('Auto Top Up', 'Automated CC top up'), ('Congress Entry', 'Entry to a congress'), ('CC Payment', 'Credit Card payment'), ('Club Payment', 'Club game payment'), ('Club Membership', 'Club membership payment'), ('Miscellaneous', 'Miscellaneous payment')], default='Miscellaneous', max_length=20, verbose_name='Transaction Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance After Transaction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(max_length=80, null=True, verbose_name='Transaction Description'),
        ),
    ]
