# Generated by Django 2.1 on 2020-04-26 00:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0012_auto_20200426_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='StripeTransaction',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='transaction',
            new_name='stripe_transaction',
        ),
    ]
