# Generated by Django 2.1 on 2020-04-26 01:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0013_auto_20200426_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='InternalTransaction',
        ),
    ]
