# Generated by Django 2.1 on 2020-04-29 00:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0015_auto_20200426_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalTransaction',
            new_name='MemberTransaction',
        ),
    ]
