# Generated by Django 2.1 on 2020-04-29 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_auto_20200428_1116'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0017_auto_20200429_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Balance After Transaction')),
                ('description', models.CharField(max_length=80, null=True, verbose_name='Transaction Description')),
                ('counterparty', models.CharField(max_length=80, null=True, verbose_name='Counterparty')),
                ('reference_no', models.CharField(max_length=14, verbose_name='Reference No')),
                ('type', models.CharField(choices=[('Transfer Out', 'Money transfered out of account'), ('Transfer In', 'Money transfered in to account'), ('Auto Top Up', 'Automated CC top up'), ('Congress Entry', 'Entry to a congress'), ('CC Payment', 'Credit Card payment'), ('Club Payment', 'Club game payment'), ('Club Membership', 'Club membership payment'), ('Miscellaneous', 'Miscellaneous payment')], max_length=20, verbose_name='Transaction Type')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_org', to='organisations.Organisation')),
                ('other_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_org', to='organisations.Organisation')),
                ('stripe_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.StripeTransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
