# Generated by Django 2.1 on 2020-04-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_organisationtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membertransaction',
            name='counterparty',
        ),
        migrations.RemoveField(
            model_name='organisationtransaction',
            name='counterparty',
        ),
    ]
