# Generated by Django 2.1 on 2020-04-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20200429_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotopupconfig',
            name='stripe_exp_month',
            field=models.IntegerField(null=True, verbose_name='Card Expiry Month'),
        ),
        migrations.AddField(
            model_name='autotopupconfig',
            name='stripe_exp_year',
            field=models.IntegerField(null=True, verbose_name='Card Expiry Year'),
        ),
        migrations.AddField(
            model_name='autotopupconfig',
            name='stripe_last4',
            field=models.CharField(max_length=4, null=True, verbose_name='Card Last 4 Digits'),
        ),
    ]
