# Generated by Django 2.1 on 2020-04-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_auto_20200429_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotopupconfig',
            name='stripe_exp_month',
        ),
        migrations.RemoveField(
            model_name='autotopupconfig',
            name='stripe_exp_year',
        ),
        migrations.RemoveField(
            model_name='autotopupconfig',
            name='stripe_last4',
        ),
        migrations.AddField(
            model_name='organisationtransaction',
            name='payment_date',
            field=models.DateTimeField(null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='organisationtransaction',
            name='payment_reference',
            field=models.CharField(max_length=10, null=True, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='organisationtransaction',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=6, verbose_name='Payment Status'),
        ),
    ]
