# Generated by Django 2.1 on 2020-05-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20200502_1048'),
        ('payments', '0023_auto_20200505_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='linked_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Linked Amount'),
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='linked_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.Organisation'),
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='linked_transaction_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Linked Transaction Type'),
        ),
        migrations.AlterField(
            model_name='membertransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='organisationtransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Reference No'),
        ),
    ]
