# Generated by Django 2.1 on 2020-05-06 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20200506_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotopupconfig',
            name='auto_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2000)], verbose_name='Auto Top Up Amount'),
        ),
    ]
