# Generated by Django 2.1 on 2020-05-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_auto_20200506_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autotopupconfig',
            name='member',
        ),
        migrations.DeleteModel(
            name='AutoTopUpConfig',
        ),
    ]
