# Generated by Django 2.2.12 on 2020-05-24 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0028_auto_20200521_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='linked_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stripetransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
