# Generated by Django 2.2.12 on 2020-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_auto_20200524_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertransaction',
            name='type',
            field=models.CharField(choices=[('Transfer Out', 'Money transfered out of account'), ('Transfer In', 'Money transfered in to account'), ('Auto Top Up', 'Automated CC top up'), ('Manual Top Up', 'Manual CC top up'), ('Congress Entry', 'Entry to a congress'), ('CC Payment', 'Credit Card payment'), ('Club Payment', 'Club game payment'), ('Club Membership', 'Club membership payment'), ('Pay a Friend', 'Payment to another member'), ('Miscellaneous', 'Miscellaneous payment')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='organisationtransaction',
            name='type',
            field=models.CharField(choices=[('Transfer Out', 'Money transfered out of account'), ('Transfer In', 'Money transfered in to account'), ('Auto Top Up', 'Automated CC top up'), ('Manual Top Up', 'Manual CC top up'), ('Congress Entry', 'Entry to a congress'), ('CC Payment', 'Credit Card payment'), ('Club Payment', 'Club game payment'), ('Club Membership', 'Club membership payment'), ('Pay a Friend', 'Payment to another member'), ('Miscellaneous', 'Miscellaneous payment')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
