# Generated by Django 2.2.12 on 2020-05-26 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_auto_20200524_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertransaction',
            name='type',
            field=models.CharField(choices=[('Transfer Out', 'Money transferred out of account'), ('Transfer In', 'Money transferred in to account'), ('Auto Top Up', 'Automated CC top up'), ('Manual Top Up', 'Manual CC top up'), ('Congress Entry', 'Entry to a congress'), ('CC Payment', 'Credit Card payment'), ('Club Payment', 'Club game payment'), ('Club Membership', 'Club membership payment'), ('Pay a Friend', 'Payment to another member'), ('Miscellaneous', 'Miscellaneous payment')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='organisationtransaction',
            name='type',
            field=models.CharField(choices=[('Transfer Out', 'Money transferred out of account'), ('Transfer In', 'Money transferred in to account'), ('Auto Top Up', 'Automated CC top up'), ('Manual Top Up', 'Manual CC top up'), ('Congress Entry', 'Entry to a congress'), ('CC Payment', 'Credit Card payment'), ('Club Payment', 'Club game payment'), ('Club Membership', 'Club membership payment'), ('Pay a Friend', 'Payment to another member'), ('Miscellaneous', 'Miscellaneous payment')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='stripetransaction',
            name='member',
            field=models.ForeignKey(blank=True, help_text='User object associated with this transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
