# Generated by Django 2.2.13 on 2020-06-25 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0032_auto_20200526_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertransaction",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="membertransaction",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="membertransaction",
            name="other_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="other_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="membertransaction",
            name="stripe_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.StripeTransaction",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_org",
                to="organisations.Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="other_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secondary_org",
                to="organisations.Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="stripe_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.StripeTransaction",
            ),
        ),
        migrations.AlterField(
            model_name="stripetransaction",
            name="linked_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linked_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stripetransaction",
            name="member",
            field=models.ForeignKey(
                blank=True,
                help_text="User object associated with this transaction",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="main_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
