# Generated by Django 3.0.9 on 2020-11-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0036_auto_20200709_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Transfer Out", "Money transferred out of account"),
                    ("Transfer In", "Money transferred in to account"),
                    ("Auto Top Up", "Automated CC top up"),
                    ("Manual Top Up", "Manual CC top up"),
                    ("Congress Entry", "Entry to an event"),
                    ("CC Payment", "Credit Card payment"),
                    ("Club Payment", "Club game payment"),
                    ("Club Membership", "Club membership payment"),
                    ("Member Transfer", "Payment to another member"),
                    ("Miscellaneous", "Miscellaneous payment"),
                    ("Settlement", "Settlement payment"),
                    ("Manual Adjustment", "Manual adjustment"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Transfer Out", "Money transferred out of account"),
                    ("Transfer In", "Money transferred in to account"),
                    ("Auto Top Up", "Automated CC top up"),
                    ("Manual Top Up", "Manual CC top up"),
                    ("Congress Entry", "Entry to an event"),
                    ("CC Payment", "Credit Card payment"),
                    ("Club Payment", "Club game payment"),
                    ("Club Membership", "Club membership payment"),
                    ("Member Transfer", "Payment to another member"),
                    ("Miscellaneous", "Miscellaneous payment"),
                    ("Settlement", "Settlement payment"),
                    ("Manual Adjustment", "Manual adjustment"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
    ]
