# Generated by Django 3.0.9 on 2020-12-12 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0038_auto_20201202_1115"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Create Date"
                    ),
                ),
                (
                    "event",
                    models.TextField(blank=True, null=True, verbose_name="Event"),
                ),
            ],
        ),
    ]
