# Generated by Django 3.0.9 on 2020-12-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0039_stripelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripelog",
            name="type",
            field=models.TextField(blank=True, null=True, verbose_name="Type"),
        ),
    ]
