# Generated by Django 3.0.9 on 2020-12-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0042_auto_20201213_0914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertransaction",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Transaction Description",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Transaction Description",
            ),
        ),
    ]
