# Generated by Django 3.0.9 on 2020-12-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0043_auto_20201217_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertransaction",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Transaction Description"
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Transaction Description"
            ),
        ),
        migrations.AlterField(
            model_name="stripetransaction",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
