# Generated by Django 3.0.9 on 2020-12-21 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0044_auto_20201221_1504"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentStatic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="Status")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Create Date"
                    ),
                ),
                (
                    "default_org_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Default Organisation Fee Percent",
                    ),
                ),
                (
                    "stripe_cost_per_transaction",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Stripe Fee Per Transaction",
                    ),
                ),
                (
                    "stripe_percentage_charge",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=8,
                        verbose_name="Stripe Fee Percentage Charge",
                    ),
                ),
            ],
        ),
    ]
