# Generated by Django 3.0.9 on 2020-12-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0045_paymentstatic"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripetransaction",
            name="stripe_balance_transaction",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Stripe Balance Transaction",
            ),
        ),
    ]
