# Generated by Django 3.0.9 on 2020-12-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_auto_20200801_1426"),
        ("payments", "0046_stripetransaction_stripe_balance_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstatic",
            name="default_org_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name="Default Organisation Settlement Fee Percent",
            ),
        ),
        migrations.CreateModel(
            name="OrganisationSettlementFees",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_fee_percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Organisation Settlement Fee Percent",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.Organisation",
                    ),
                ),
            ],
        ),
    ]
