# Generated by Django 3.0.9 on 2020-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0047_auto_20201221_1727"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentstatic",
            name="status",
        ),
        migrations.AddField(
            model_name="paymentstatic",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Active"),
            preserve_default=False,
        ),
    ]
