# Generated by Django 3.0.9 on 2020-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0048_auto_20201221_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstatic",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
