# Generated by Django 3.0.9 on 2020-12-21 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0049_auto_20201221_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentstatic",
            name="modified_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentstatic",
            name="default_org_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name="Settlement Fee Percent for organisations (default)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatic",
            name="stripe_cost_per_transaction",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=8,
                verbose_name="Stripe Fee Per Transaction $",
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatic",
            name="stripe_percentage_charge",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=8,
                verbose_name="Stripe Fee Percentage (per transaction)",
            ),
        ),
    ]
