# Generated by Django 3.0.9 on 2020-12-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_auto_20200801_1426"),
        ("payments", "0050_auto_20201221_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationsettlementfees",
            name="organisation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.Organisation",
            ),
        ),
        migrations.AlterField(
            model_name="paymentstatic",
            name="default_org_fee_percent",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                verbose_name="ABF Settlement Fee Percent for Organisations (default)",
            ),
        ),
    ]
