# Generated by Django 3.0.9 on 2020-12-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0051_auto_20201222_0951"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationsettlementfees",
            options={"verbose_name_plural": "organisation settlement fees"},
        ),
    ]
