# Generated by Django 3.0.9 on 2021-06-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0052_auto_20201222_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripetransaction",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Refund Amount",
            ),
        ),
        migrations.AddField(
            model_name="stripetransaction",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("Not Refunded", "Not refunded"),
                    ("Partial", "Partial refund paid"),
                    ("Full", "Fully refunded"),
                ],
                default="Not Refunded",
                max_length=12,
                verbose_name="Refund Status",
            ),
        ),
    ]
