# Generated by Django 3.2.4 on 2021-06-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0055_auto_20210604_1055"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentstatic",
            name="stripe_refund_percentage_charge",
            field=models.DecimalField(
                decimal_places=4,
                default=3.0,
                max_digits=8,
                verbose_name="Percentage to charge members for refunds",
            ),
        ),
        migrations.AddField(
            model_name="paymentstatic",
            name="stripe_refund_weeks",
            field=models.IntegerField(
                default=12, verbose_name="Number of weeks ago to allow refund"
            ),
        ),
    ]
