# Generated by Django 3.2.4 on 2021-06-15 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0056_auto_20210609_1226"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripetransaction",
            name="refund_status",
        ),
        migrations.AlterField(
            model_name="paymentstatic",
            name="modified_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="stripetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiated", "Initiated - Stripe Transaction object created"),
                    ("Intent", "Intent - received customer intent to pay from Stripe"),
                    (
                        "Pending",
                        "Pending - transaction approved by Stripe - awaiting confirmation",
                    ),
                    ("Success", "Success - payment completed successfully"),
                    ("Failed", "Failed - payment failed"),
                    ("Partial Refund", "Partially refunded"),
                    ("Full Refund", "Fully refunded"),
                ],
                default="Initiated",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
