# Generated by Django 3.2.4 on 2021-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0057_auto_20210615_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiated", "Initiated - Stripe Transaction object created"),
                    ("Intent", "Intent - received customer intent to pay from Stripe"),
                    (
                        "Pending",
                        "Pending - transaction approved by Stripe - awaiting confirmation",
                    ),
                    ("Succeeded", "Succeeded - payment completed successfully"),
                    ("Failed", "Failed - payment failed"),
                    ("Partial refund", "Partial refund - some money returned"),
                    ("Refunded", "Refunded - Fully refunded"),
                ],
                default="Initiated",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
