# Generated by Django 3.2.4 on 2021-09-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0061_organisationtransaction_bank_settlement_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationtransaction",
            name="bank_settlement_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Bank Settlement Amount",
            ),
        ),
    ]
