# Generated by Django 3.2.5 on 2021-10-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0034_organisationfrontpage"),
        ("payments", "0063_orgpaymentmethod_userpendingpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgpaymentmethod",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="orgpaymentmethod",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
    ]
