# Generated by Django 3.2.13 on 2022-07-07 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0065_auto_20220706_1706"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpendingpayment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
