# Generated by Django 3.2.13 on 2022-07-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0067_auto_20220709_0945"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertransaction",
            name="club_session_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
