# Generated by Django 3.2.13 on 2022-07-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0068_membertransaction_club_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membertransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Transfer Out", "Money transferred out of account"),
                    ("Transfer In", "Money transferred in to account"),
                    ("Auto Top Up", "Automated CC top up"),
                    ("Manual Top Up", "Manual CC top up"),
                    ("Congress Entry", "Entry to an event"),
                    ("CC Payment", "Credit Card payment"),
                    ("Club Payment", "Club game payment"),
                    ("Club Top Up", "Club Top Up"),
                    ("Club Membership", "Club membership payment"),
                    ("Member Transfer", "Payment to another member"),
                    ("Miscellaneous", "Miscellaneous payment"),
                    ("Settlement", "Settlement payment"),
                    ("Manual Adjustment", "Manual adjustment"),
                    ("Org Transfer", "Organisation Transfer"),
                    ("Refund", "Refund"),
                    ("Card Refund", "Refund to a card"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
        migrations.AlterField(
            model_name="organisationtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Transfer Out", "Money transferred out of account"),
                    ("Transfer In", "Money transferred in to account"),
                    ("Auto Top Up", "Automated CC top up"),
                    ("Manual Top Up", "Manual CC top up"),
                    ("Congress Entry", "Entry to an event"),
                    ("CC Payment", "Credit Card payment"),
                    ("Club Payment", "Club game payment"),
                    ("Club Top Up", "Club Top Up"),
                    ("Club Membership", "Club membership payment"),
                    ("Member Transfer", "Payment to another member"),
                    ("Miscellaneous", "Miscellaneous payment"),
                    ("Settlement", "Settlement payment"),
                    ("Manual Adjustment", "Manual adjustment"),
                    ("Org Transfer", "Organisation Transfer"),
                    ("Refund", "Refund"),
                    ("Card Refund", "Refund to a card"),
                ],
                max_length=20,
                verbose_name="Transaction Type",
            ),
        ),
    ]
