# Generated by Django 3.2.15 on 2023-01-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0071_auto_20221207_1024"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractFinanceClassification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CO", "Congress"), ("SE", "Session")], max_length=2
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.organisationtransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinanceClassificationCategory",
            fields=[
                (
                    "abstractfinanceclassification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.abstractfinanceclassification",
                    ),
                ),
            ],
            bases=("payments.abstractfinanceclassification",),
        ),
        migrations.CreateModel(
            name="FinanceClassificationSubCategory",
            fields=[
                (
                    "abstractfinanceclassification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.abstractfinanceclassification",
                    ),
                ),
                ("sub_category", models.CharField(max_length=50)),
            ],
            bases=("payments.abstractfinanceclassification",),
        ),
    ]
