# Generated by Django 3.2.15 on 2023-01-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0072_abstractfinanceclassification_financeclassificationcategory_financeclassificationsubcategory",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationtransaction",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organisationtransaction",
            name="sub_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organisationtransaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("CO", "Congress"), ("SE", "Session")],
                max_length=2,
                null=True,
            ),
        ),
    ]
