# Generated by Django 3.2.15 on 2023-01-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0061_auto_20221014_0533"),
        ("payments", "0073_auto_20230120_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractfinanceclassification",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
    ]
