# Generated by Django 3.2.15 on 2023-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0076_alter_organisationtransaction_gl_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertransaction",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationtransaction",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
