# Generated by Django 3.0.8 on 2020-07-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0036_auto_20200709_1536"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0007_auto_20200722_1708"),
    ]

    operations = [
        migrations.CreateModel(
            name="Congress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Congress Year")),
                ("venue_name", models.CharField(max_length=100, verbose_name="Venue")),
                (
                    "venue_location",
                    models.CharField(max_length=100, verbose_name="Venue Location"),
                ),
                (
                    "venue_transport",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Venue Location",
                    ),
                ),
                (
                    "venue_catering",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Venue Location",
                    ),
                ),
                (
                    "venue_additonal_info",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Venue Location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CongressMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Congress Master Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(max_length=100, verbose_name="Event Name"),
                ),
                (
                    "description",
                    models.CharField(max_length=400, verbose_name="Description"),
                ),
                (
                    "max_entries",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maximum Entries"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Open", "Open"),
                            ("Restricted", "Restricted"),
                            ("Novice", "Novice"),
                            ("Senior", "Senior"),
                            ("Youth", "Youth"),
                        ],
                        max_length=14,
                        null=True,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Congress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventEntryType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_entry_type",
                    models.CharField(max_length=20, verbose_name="Event Entry Type"),
                ),
                (
                    "entry_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Full Entry Fee"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventEntryPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Entry Paid"),
                            ("Pending Manual", "Pending Manual Payment"),
                            ("Unpaid", "Entry Unpaid"),
                        ],
                        default="Unpaid",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_payment_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.MemberTransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue_transport",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Venue Location",
                    ),
                ),
                (
                    "max_entries",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maximum Entries"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Paid", "Entry Paid"),
                            ("Pending Manual", "Pending Manual Payment"),
                            ("Unpaid", "Entry Unpaid"),
                        ],
                        default="Unpaid",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CongressPeople",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_role",
                    models.CharField(max_length=50, verbose_name="User Role"),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Congress",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CongressNewsItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Congress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CongressDownloads",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.Congress",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="congress",
            name="congress_master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.CongressMaster",
            ),
        ),
        migrations.AddField(
            model_name="congress",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.Organisation",
            ),
        ),
    ]
