# Generated by Django 3.0.8 on 2020-07-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20200726_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="congress",
            name="venue_additonal_info",
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="Venue Additional Information",
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="venue_catering",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Venue Catering"
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="venue_transport",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Venue Transport"
            ),
        ),
    ]
