# Generated by Django 3.0.8 on 2020-07-27 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20200727_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="congress",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Published", "Published"),
                    ("Closed", "Closed"),
                ],
                default="Draft",
                max_length=10,
                verbose_name="Congress Status",
            ),
        ),
    ]
