# Generated by Django 3.0.8 on 2020-07-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_auto_20200730_1237"),
    ]

    operations = [
        migrations.RenameField(
            model_name="congress",
            old_name="venue_additonal_info",
            new_name="venue_additional_info",
        ),
    ]
