# Generated by Django 3.0.8 on 2020-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_auto_20200730_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="additional_info",
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="Congress Additional Information",
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="venue_transport",
            field=models.TextField(
                blank=True, null=True, verbose_name="Venue Transport"
            ),
        ),
    ]
