# Generated by Django 3.1 on 2020-08-17 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_auto_20200801_1426"),
        ("events", "0010_auto_20200806_1603"),
    ]

    operations = [
        migrations.AddField(
            model_name="congressmaster",
            name="org",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
            preserve_default=False,
        ),
    ]
