# Generated by Django 3.1 on 2020-08-17 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0010_auto_20200801_1426"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0012_auto_20200817_1456"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="general_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="General Information"
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="venue_location",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Venue Location"
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="venue_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Venue Name"
            ),
        ),
        migrations.AlterField(
            model_name="congress",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Congress Year"
            ),
        ),
    ]
