# Generated by Django 3.1 on 2020-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_auto_20200817_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="allow_partnership_desk",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="congress",
            name="default_email",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Default Email Address",
            ),
        ),
        migrations.AddField(
            model_name="congress",
            name="entry_close_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="congress",
            name="entry_open_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="congress",
            name="payment_method_bank_transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="congress",
            name="payment_method_cash",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="congress",
            name="payment_method_system_dollars",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="entry_close_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="entry_open_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
