# Generated by Django 3.1 on 2020-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_auto_20200818_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="payment_method_cheques",
            field=models.BooleanField(default=False),
        ),
    ]
