# Generated by Django 3.1 on 2020-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_congress_payment_method_cheques"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="player_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Individual", "Individual"),
                    ("Pairs", "Pairs"),
                    ("Teams", "Teams"),
                ],
                max_length=14,
                null=True,
                verbose_name="Player Format",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Description"
            ),
        ),
    ]
