# Generated by Django 3.1 on 2020-08-19 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_date",
            field=models.DateField(default=datetime.date.today()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="session",
            name="session_start",
            field=models.TimeField(default=datetime.time(16, 50, 50, 431857)),
        ),
    ]
