# Generated by Django 3.1 on 2020-08-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_auto_20200819_1651"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="congress",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session", name="session_start", field=models.TimeField(),
        ),
    ]
