# Generated by Django 3.0.9 on 2020-08-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_auto_20200820_0823"),
    ]

    operations = [
        migrations.RemoveField(model_name="congress", name="org",),
        migrations.AddField(
            model_name="congress",
            name="sponsors",
            field=models.TextField(blank=True, null=True, verbose_name="Sponsors"),
        ),
    ]
