# Generated by Django 3.0.9 on 2020-08-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_congress_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="allow_early_payment_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="entry_early_payment_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Early Payment Discount",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="entry_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Entry Fee",
            ),
        ),
    ]
