# Generated by Django 3.0.9 on 2020-08-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_auto_20200824_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entry_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Entry Fee"
            ),
            preserve_default=False,
        ),
    ]
