# Generated by Django 3.0.9 on 2020-08-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_auto_20200824_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="early_payment_discount_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last day for early discount"
            ),
        ),
    ]
