# Generated by Django 3.0.9 on 2020-08-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_auto_20200824_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="senior_age",
            field=models.IntegerField(default=30, verbose_name="Cut off age"),
        ),
        migrations.AddField(
            model_name="congress",
            name="senior_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date for age check"
            ),
        ),
    ]
