# Generated by Django 3.0.9 on 2020-08-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_auto_20200824_1152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="senior_age",
            field=models.IntegerField(default=60, verbose_name="Cut off age"),
        ),
    ]
