# Generated by Django 3.0.9 on 2020-08-24 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0028_auto_20200824_1153"),
    ]

    operations = [
        migrations.RemoveField(model_name="evententry", name="max_entries",),
        migrations.RemoveField(model_name="evententryplayer", name="event",),
        migrations.AddField(
            model_name="evententry",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("System dollars", "ABF $"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
        migrations.AddField(
            model_name="evententry",
            name="primary_entrant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evententryplayer",
            name="event_entry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.EventEntry",
            ),
            preserve_default=False,
        ),
    ]
