# Generated by Django 3.0.9 on 2020-08-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0029_auto_20200825_0611"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="entry_youth_payment_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Youth Discount",
            ),
        ),
    ]
