# Generated by Django 3.0.9 on 2020-08-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_event_entry_youth_payment_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="bank_transfer_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bank Transfer Details"
            ),
        ),
        migrations.AddField(
            model_name="congress",
            name="cheque_details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cheque Details"
            ),
        ),
    ]
