# Generated by Django 3.0.9 on 2020-08-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0031_auto_20200825_1424"),
    ]

    operations = [
        migrations.RemoveField(model_name="evententry", name="payment_type",),
        migrations.AddField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("System dollars", "ABF $"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Cash", "Cash"),
                    ("Cheque", "Cheque"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
    ]
