# Generated by Django 3.0.9 on 2020-08-31 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0034_auto_20200831_1101"),
    ]

    operations = [
        migrations.RemoveField(model_name="basketitem", name="basket",),
        migrations.AddField(
            model_name="basketitem",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Basket",),
    ]
