# Generated by Django 3.0.9 on 2020-08-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0037_auto_20200831_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("system-dollars-me", "My ABF $"),
                    ("system-dollars-them", "Their ABF $"),
                    ("bank-transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
    ]
