# Generated by Django 3.0.9 on 2020-08-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0038_auto_20200831_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententryplayer",
            name="batch_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Payment Batch ID"
            ),
        ),
    ]
