# Generated by Django 3.0.9 on 2020-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0039_evententryplayer_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("my-system-dollars", "My ABF $"),
                    ("their-system-dollars", "Their ABF $"),
                    ("bank-transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
    ]
