# Generated by Django 3.0.9 on 2020-08-31 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0040_auto_20200831_1853"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="entry_complete_date",),
        migrations.RemoveField(model_name="event", name="first_created_date",),
        migrations.AddField(
            model_name="evententry",
            name="entry_complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evententry",
            name="first_created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
