# Generated by Django 3.0.9 on 2020-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0041_auto_20200831_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="player_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Individual", "Individual"),
                    ("Pairs", "Pairs"),
                    ("Teams of 3", "Teams of Three"),
                    ("Teams", "Teams"),
                ],
                max_length=14,
                null=True,
                verbose_name="Player Format",
            ),
        ),
    ]
