# Generated by Django 3.0.9 on 2020-09-27 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0043_auto_20200918_1013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="player_format",
            field=models.CharField(
                choices=[
                    ("Individual", "Individual"),
                    ("Pairs", "Pairs"),
                    ("Teams of 3", "Teams of Three"),
                    ("Teams", "Teams"),
                ],
                default="Teams",
                max_length=14,
                verbose_name="Player Format",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("my-system-dollars", "My ABF $ (Credit Card)"),
                    ("their-system-dollars", "Their ABF $"),
                    ("other-system-dollars", "Default"),
                    ("bank-transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=30, verbose_name="Event Category"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
            ],
        ),
    ]
