# Generated by Django 3.0.9 on 2020-09-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0046_playerbatchid"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententryplayer",
            name="payment_received",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Payment Received",
            ),
        ),
    ]
