# Generated by Django 3.0.9 on 2020-09-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0047_evententryplayer_payment_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententryplayer",
            name="reason",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Entry Fee Reason"
            ),
        ),
        migrations.AlterField(
            model_name="evententryplayer",
            name="batch_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Payment Batch ID"
            ),
        ),
    ]
