# Generated by Django 3.0.9 on 2020-10-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0049_eventlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="batch_id",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Payment Batch ID"
            ),
        ),
        migrations.AlterField(
            model_name="playerbatchid",
            name="batch_id",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Payment Batch ID"
            ),
        ),
    ]
