# Generated by Django 3.0.9 on 2020-10-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0051_auto_20201003_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entry_youth_payment_discount",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Youth Discount Percentage"
            ),
        ),
    ]
