# Generated by Django 3.0.9 on 2020-10-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0052_auto_20201006_1219"),
    ]

    operations = [
        migrations.RemoveField(model_name="congress", name="default_email",),
    ]
