# Generated by Django 3.0.9 on 2020-10-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0054_auto_20201013_1041"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="name",
            field=models.CharField(
                default="unset", max_length=100, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
