# Generated by Django 3.0.9 on 2020-10-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_auto_20201016_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entry_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
