# Generated by Django 3.0.9 on 2020-10-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0057_auto_20201016_1401"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evententry",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="evententry",
            name="entry_status",
            field=models.CharField(
                choices=[("Incomplete", "Incomplete"), ("Complete", "Complete")],
                default="Incomplete",
                max_length=20,
                verbose_name="Entry Status",
            ),
        ),
    ]
