# Generated by Django 3.0.9 on 2020-10-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0058_auto_20201019_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_received",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Payment Received",
            ),
        ),
    ]
