# Generated by Django 3.0.9 on 2020-10-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0059_auto_20201019_1442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="people",
            field=models.TextField(
                blank=True,
                default='<table class="table"><tbody><tr><td><span style="font-weight: normal;">\nOrganiser:</span></td><td><span style="font-weight: normal;">Jane Doe</span></td>\n</tr><tr><td><span style="font-weight: normal;">Phone:</span></td><td>\n<span style="font-weight: normal;">040404040444</span></td></tr><tr><td>\n<span style="font-weight: normal;">Email:</span></td><td><span style="font-weight: normal;">\nme@club.com</span></td></tr><tr><td><span style="font-weight: normal;">\nChief Tournament Director:</span></td><td><span style="font-weight: normal;">\nAlan Partidge</span></td></tr></tbody></table><p><br></p>',
                null=True,
                verbose_name="People",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Restricted", "Restricted"),
                    ("Novice", "Novice"),
                    ("Senior", "Senior"),
                    ("Youth", "Youth"),
                    ("Rookies", "Rookies"),
                    ("Veterans", "Veterans"),
                    ("Womens", "Womens"),
                    ("Intermediate", "Intermediate"),
                ],
                max_length=14,
                null=True,
                verbose_name="Event Type",
            ),
        ),
    ]
