# Generated by Django 3.0.9 on 2020-10-20 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0060_auto_20201020_1103"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evententryplayer",
            name="player_payment_record",
        ),
        migrations.AddField(
            model_name="evententryplayer",
            name="entry_complete_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evententryplayer",
            name="first_created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="EventEntryType",
        ),
    ]
