# Generated by Django 3.0.9 on 2020-10-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0062_auto_20201020_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("my-system-dollars", "My Bridge Credits"),
                    ("their-system-dollars", "Their Bridge Credits"),
                    ("other-system-dollars", "Default"),
                    ("bank-transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
    ]
