# Generated by Django 3.0.9 on 2020-10-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0063_auto_20201022_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="event_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.EventEntry",
            ),
        ),
        migrations.AlterField(
            model_name="evententry",
            name="entry_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Entry Status",
            ),
        ),
    ]
