# Generated by Django 3.0.9 on 2020-10-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0065_eventplayerdiscount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Entry Paid"),
                    ("Pending Manual", "Pending Manual Payment"),
                    ("Unpaid", "Entry Unpaid"),
                    ("Free", "Free"),
                ],
                default="Unpaid",
                max_length=20,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("my-system-dollars", "Bridge Credits"),
                    ("their-system-dollars", "Their Bridge Credits"),
                    ("other-system-dollars", "TBA"),
                    ("bank-transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("unknown", "Unknown"),
                    ("Free", "Free"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
    ]
