# Generated by Django 3.0.9 on 2020-11-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0066_auto_20201027_1351"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="congress",
            options={"verbose_name_plural": "Congresses"},
        ),
        migrations.AlterModelOptions(
            name="evententry",
            options={"verbose_name_plural": "Event entries"},
        ),
    ]
