# Generated by Django 3.0.9 on 2020-11-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0067_auto_20201109_1002"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="bulletins",
            field=models.TextField(blank=True, null=True, verbose_name="Bulletins"),
        ),
        migrations.AlterField(
            model_name="evententryplayer",
            name="reason",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Entry Fee Reason"
            ),
        ),
    ]
