# Generated by Django 3.0.9 on 2020-11-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0069_auto_20201109_1450"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletin",
            name="description",
            field=models.CharField(default="", max_length=200, verbose_name="Reason"),
            preserve_default=False,
        ),
    ]
