# Generated by Django 3.0.9 on 2020-11-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0070_bulletin_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="document",
            field=models.FileField(upload_to="bulletins/%Y/%m/%d/"),
        ),
    ]
