# Generated by Django 3.0.9 on 2020-11-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0071_auto_20201109_1631"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="automatic_refund_cutoff",
            field=models.DateField(blank=True, null=True),
        ),
    ]
