# Generated by Django 3.0.9 on 2020-11-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0072_congress_automatic_refund_cutoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="latest",
            field=models.TextField(blank=True, null=True, verbose_name="Latest News"),
        ),
    ]
