# Generated by Django 3.0.9 on 2020-11-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0075_partnershipdesk"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnershipdesk",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Comment"),
        ),
    ]
