# Generated by Django 3.0.9 on 2020-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0076_partnershipdesk_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="player_format",
            field=models.CharField(
                choices=[("Pairs", "Pairs"), ("Teams", "Teams")],
                max_length=14,
                verbose_name="Player Format",
            ),
        ),
    ]
