# Generated by Django 3.0.9 on 2020-12-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_auto_20201117_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='player_format',
            field=models.CharField(choices=[('Pairs', 'Pairs'), ('Teams of 3', 'Teams of Three'), ('Teams', 'Teams')], max_length=14, verbose_name='Player Format'),
        ),
    ]
