# Generated by Django 3.0.9 on 2020-12-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0079_auto_20201216_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententry",
            name="notes",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Notes"
            ),
        ),
    ]
