# Generated by Django 3.0.9 on 2020-12-22 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0082_auto_20201221_1504"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="congressdownload",
            name="text",
        ),
        migrations.AddField(
            model_name="congressdownload",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="congressdownload",
            name="description",
            field=models.CharField(
                default="", max_length=200, verbose_name="Description"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="congressdownload",
            name="document",
            field=models.FileField(
                default="", upload_to="congress-downloads/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
    ]
