# Generated by Django 3.0.9 on 2021-01-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_auto_20201222_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='congress',
            name='payment_method_off_system_pp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evententryplayer',
            name='payment_type',
            field=models.CharField(choices=[('my-system-dollars', 'Bridge Credits'), ('their-system-dollars', 'Their Bridge Credits'), ('other-system-dollars', 'TBA'), ('bank-transfer', 'Bank Transfer'), ('off-system-pp', 'Off System Pre-paid'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('unknown', 'Unknown'), ('Free', 'Free')], default='Unknown', max_length=20, verbose_name='Payment Type'),
        ),
    ]
