# Generated by Django 3.0.9 on 2021-01-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0084_auto_20210114_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententryplayer",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("my-system-dollars", "Bridge Credits"),
                    ("their-system-dollars", "Their Bridge Credits"),
                    ("other-system-dollars", "TBA"),
                    ("bank-transfer", "Bank Transfer"),
                    ("off-system-pp", "Club PP System"),
                    ("cash", "Cash"),
                    ("cheque", "Cheque"),
                    ("unknown", "Unknown"),
                    ("Free", "Free"),
                ],
                default="Unknown",
                max_length=20,
                verbose_name="Payment Type",
            ),
        ),
    ]
