# Generated by Django 3.0.9 on 2021-04-09 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0086_auto_20210217_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evententryplayer',
            name='player_comment',
        ),
        migrations.AlterField(
            model_name='event',
            name='entry_early_payment_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Early Payment Discount'),
        ),
    ]
