# Generated by Django 3.0.9 on 2021-05-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_auto_20210521_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='allow_youth_payment_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
