# Generated by Django 3.0.9 on 2021-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_auto_20210522_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='allow_youth_payment_discount',
            field=models.BooleanField(default=False),
        ),
    ]
