# Generated by Django 3.2.4 on 2021-06-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_auto_20210522_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congress',
            name='people',
            field=models.TextField(blank=True, default='<table class="table"><tbody><tr><td><span style="font-weight: normal;">\nOrganiser:</span></td><td><span style="font-weight: normal;">Jane Doe</span></td>\n</tr><tr><td><span style="font-weight: normal;">Phone:</span></td><td>\n<span style="font-weight: normal;">040404040444</span></td></tr><tr><td>\n<span style="font-weight: normal;">Email:</span></td><td><span style="font-weight: normal;">\nme@club.com</span></td></tr><tr><td><span style="font-weight: normal;">\nChief Tournament Director:</span></td><td><span style="font-weight: normal;">\nAlan Partridge</span></td></tr></tbody></table><p><br></p>', null=True, verbose_name='People'),
        ),
    ]
