# Generated by Django 3.2.4 on 2021-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0093_alter_congress_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Open", "Open"),
                    ("Restricted", "Restricted"),
                    ("Novice", "Novice"),
                    ("Senior", "Senior"),
                    ("Youth", "Youth"),
                    ("Rookies", "Rookies"),
                    ("Veterans", "Veterans"),
                    ("Womens", "Womens"),
                    ("Intermediate", "Intermediate"),
                    ("Mixed", "Mixed"),
                ],
                max_length=14,
                null=True,
                verbose_name="Event Type",
            ),
        ),
    ]
