# Generated by Django 3.2.4 on 2021-06-25 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0095_alter_event_congress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententry",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="events.event"
            ),
        ),
        migrations.AlterField(
            model_name="evententry",
            name="primary_entrant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
