# Generated by Django 3.2.4 on 2021-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0096_auto_20210626_0954"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
