# Generated by Django 3.2.5 on 2021-10-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0097_congress_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entry_youth_payment_discount",
            field=models.IntegerField(
                default=50, verbose_name="Youth Discount Percentage"
            ),
        ),
    ]
