# Generated by Django 3.2.5 on 2021-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0099_event_entry_close_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_team_names",
            field=models.BooleanField(default=False),
        ),
    ]
