# Generated by Django 3.2.5 on 2021-11-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0100_event_allow_team_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententry",
            name="team_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
