# Generated by Django 3.2.5 on 2021-11-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0101_evententry_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententryplayer",
            name="override_tba_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="evententryplayer",
            name="override_tba_system_number",
            field=models.IntegerField(default=0),
        ),
    ]
