# Generated by Django 3.2.5 on 2021-11-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0102_auto_20211107_1817"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="list_priority_order",
            field=models.IntegerField(default=0),
        ),
    ]
