# Generated by Django 3.2.12 on 2022-03-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0103_event_list_priority_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="congress_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("national_gold", "National gold point"),
                    ("state_championship", "State championship"),
                    ("state_congress", "State congress"),
                    ("club", "Club event"),
                    ("club_congress", "Club congress"),
                    ("lesson", "Lesson"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
                verbose_name="Congress Type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="player_format",
            field=models.CharField(
                choices=[
                    ("Individual", "Individual"),
                    ("Pairs", "Pairs"),
                    ("Teams of 3", "Teams of Three"),
                    ("Teams", "Teams"),
                ],
                max_length=14,
                verbose_name="Player Format",
            ),
        ),
    ]
