# Generated by Django 3.2.14 on 2022-08-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0105_alter_congress_congress_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="denormalised_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="denormalised_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="denormalised_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="denormalised_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
