# Generated by Django 3.2.15 on 2023-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0107_alter_congress_congress_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="congress_venue_type",
            field=models.CharField(
                choices=[
                    ("F", "Face To Face"),
                    ("O", "Online"),
                    ("M", "Mixed"),
                    ("U", "Unknown"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
