# Generated by Django 3.2.15 on 2023-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0108_congress_congress_venue_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="congress_venue_type",
            field=models.CharField(
                choices=[
                    ("F", "Face-to-Face"),
                    ("O", "Online"),
                    ("M", "Mixed"),
                    ("U", "Unknown"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
