# Generated by Django 3.2.15 on 2023-01-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0110_congress_do_not_auto_close_congress"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="online_platform",
            field=models.CharField(
                choices=[
                    ("B", "Bbo"),
                    ("R", "RealBridge"),
                    ("S", "StepBridge"),
                    ("U", "Unknown"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
