# Generated by Django 3.2.15 on 2023-02-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0111_congress_online_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="online_platform",
            field=models.CharField(
                choices=[
                    ("B", "BBO"),
                    ("R", "RealBridge"),
                    ("S", "StepBridge"),
                    ("U", "Unknown"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
