# Generated by Django 3.2.15 on 2023-03-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0113_auto_20230329_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententry",
            name="entry_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                    ("Cancelled", "Cancelled"),
                    ("In Cart", "In Basket"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Entry Status",
            ),
        ),
    ]
