# Generated by Django 3.2.19 on 2024-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0116_remove_congress_automatically_mark_club_pp_as_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="congress",
            name="online_platform",
            field=models.CharField(
                choices=[
                    ("B", "BBO"),
                    ("R", "RealBridge"),
                    ("S", "StepBridge"),
                    ("T", "Microsoft Teams"),
                    ("Z", "Zoom"),
                    ("U", "Unknown"),
                ],
                default="U",
                max_length=1,
            ),
        ),
    ]
