# Generated by Django 3.2.19 on 2024-06-04 01:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0117_alter_congress_online_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="allow_member_entry_fee",
            field=models.BooleanField(
                default=False, verbose_name="Allow Member Specific Entry Fee"
            ),
        ),
        migrations.AddField(
            model_name="congress",
            name="members_only",
            field=models.BooleanField(default=False, verbose_name="Members Only"),
        ),
        migrations.AddField(
            model_name="event",
            name="member_entry_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                null=True,
                verbose_name="Member Entry Fee",
            ),
        ),
    ]
