# Generated by Django 3.2.19 on 2024-06-04 04:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0118_auto_20240604_1100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="entry_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
                null=True,
                verbose_name="Entry Fee",
            ),
        ),
    ]
