#!/bin/sh

# about: shows this help screen

. utils/cgit/_cgit_include_vars
. utils/cgit/_cgit_reload

cat << EOF

CGIT - Cobalt Git Commands

These cgit commands automate the Git and Elastic Beanstalk commands used for standard activities.

For most commands to work you will need to be on the relevant branch.
Use git checkout [branch] if necessary.

EOF

for filename in utils/cgit/cgit_*; do
  file="$(basename "$filename")"
  about="$(grep -i about: "$filename" | grep -v cgit_help | cut -d' ' -f3-)"
  printf "%-40s" "$file"
  echo "- $about"
done

echo ""
echo "Current Status"
echo "--------------"

# Be careful with AWS env variables
unset AWS_SECRET_ACCESS_KEY
unset AWS_ACCESS_KEY_ID

# Get this branch
BRANCH=$(git branch --show-current)

# Function to work with environments
get_status() {
  THISNAME=$1
  THISSEARCH=$2
  REFBRANCH=$3

  # Get full environment name from ebcli
  THISENV=$(eb list | grep $THISSEARCH | tr \* " ")

  # Get which application is installed on this environment
  APP=$(eb status $THISENV | grep Deploy | awk '{print $3}')

  # Use aws cli to get the description for this application
  DESC=$(aws elasticbeanstalk describe-application-versions --version-label "$APP" | grep Description | awk '{print $2}' | tr -d '"' | tr -d ,)

  # Description is branch@timestamp - get branch
  THISBRANCH=$(echo $DESC | tr '@' ' ' | awk '{print $1}')

  # Make sure we have latest copy of branch for reference
  git fetch origin $THISBRANCH >/dev/null 2>&1

  # See how many files different from reference branch
  FILE_DIFF=$(git diff --name-status $THISBRANCH..$REFBRANCH | wc | awk '{print $1}')

  # Get the timestamp from the description and replace _ with space
  TIMESTAMP=$(echo $DESC|cut -d@ -f2 | tr '_' ' ')

  # Print summary
    printf "%-15s" "$THISNAME"
  printf "is running: ${YELLOW}%-20s${NC}" "${THISBRANCH}"
  printf "Release Date: ${BLUE}${TIMESTAMP}${NC} [$FILE_DIFF files different from $REFBRANCH]\n"
}

get_status "Test" "cobalt-test" "$BRANCH"
get_status "UAT" "cobalt-uat" "develop"
get_status "Production" "cobalt-production" "develop"


