#!/bin/bash

# Compare current branch with a released branch

BRANCH=$(git branch --show-current)

echo "You are on branch $BRANCH"
echo ""

OLD_BRANCH=$(cgit_branch_for_environment $* | tail -1)

if [ $? -eq 0 ]
then
  cgit_compare "$BRANCH" "$OLD_BRANCH"
fi