#!/bin/bash

RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Compare 2 branches
OLD=$1
NEW=$2

if [ $# -lt 2 ]
then
  echo "Usage: $0 new_branch old_branch --ignore 'pattern'"
  echo ""
  echo "e.g. $0 develop release/1.1.1 --ignore '^static'"
  echo "e.g. $0 develop release/1.1.2 --ignore '^static|html$|docs'"
  exit
fi

if [[ -z $(git status -s) ]]
then
  # Nothing
  echo ""
else
  printf "\n\n${BLUE}WARNING!!!${NC}: ${RED}Unsaved changes in current branch.${NC} These won't be included.\n\n"
  git status
  read -p "Press key to continue..." -n1 -s
  echo ""
  echo "Running..."
fi

# Format the HTML Template
cp utils/cgit/tools/cgit_template.html /tmp/temp.html
# Use # as sed character since / will be in release branch
sed -i -e "s#!!BRANCH!!#$OLD#g" /tmp/temp.html
sed -i -e "s#!!OTHERBRANCH!!#$NEW#g" /tmp/temp.html

if [ $# -gt 2 ]
then
git diff $NEW $OLD --name-only | grep -Ev $4 | xargs git diff $NEW -- | diff2html -i stdin -s side --su open --htmlWrapperTemplate /tmp/temp.html
else
  git diff -w $NEW $OLD | diff2html -i stdin -s side --su open --htmlWrapperTemplate /tmp/temp.html
fi