#!/bin/bash

# Compare current branch with a released branch

BRANCH=$(git branch --show-current)

echo "You are on branch $BRANCH"
echo ""

if [ $# -ne 1 ]
 then

# Prompt for environment if not provided as a parameter

  PS3='Choose an environment to compare to: '
  options=("test" "uat" "production" "Quit")
  select opt in "${options[@]}"
  do
      case $opt in
          "test")
              ENV="test"
              break
              ;;
          "uat")
              ENV="uat"
              break
              ;;
          "production")
              ENV="production"
              break
              ;;
          "Quit")
              exit
              ;;
          *) echo "invalid option $REPLY";;
      esac
  done

else
  ENV=$1   # Passed as parameter
fi


echo "Getting current $ENV branch..."

# get full name of environment e.g. test -> cobalt-test-black
THISENV=$(eb list | grep cobalt-$ENV | tr \* " ")

# Get the deployed version on this environment
APP=$(eb status $THISENV | grep Deploy | awk '{print $3}')

# Get the description from aws cli
DESC=$(aws elasticbeanstalk describe-application-versions --version-label "$APP" | grep Description | awk '{print $2}' | tr -d '"' | tr -d ,)

# Now we should have branch@time - we just want branch
THISBRANCH=$(echo $DESC | tr '@' ' ' | awk '{print $1}')

echo "$ENV is running $THISBRANCH. This assumes cgit has been used for deployment"

echo "Getting $THISBRANCH..."
git fetch origin $THISBRANCH

# Now run the diff
diff2html -s side --su open -- -M $THISBRANCH >/dev/null 2>&1

# rc=3 is no output - usually because the branch doesn't exist or is the same
if [ $? -eq 3 ];then

 # check if branches are the same
 DIFFS=$(git diff $BRANCH $THISBRANCH | wc | awk '{print $1}')

 if [ "$DIFFS" -eq "0" ]; then
   echo "Branches are the same ($BRANCH = $THISBRANCH)"
 else
   echo "Error occurred. Try running 'diff2html -s side --su open -- -M $THISBRANCH'"
 fi

 exit 1
fi