#!/bin/bash

# about: basic test of production for use after a release or any time there is concern\n

read -p "Userid: " USERID

read -s -p "Password: " PASSWORD

echo ""
echo ""

./manage.py smoke_test --password=$PASSWORD --userid=$USERID --script=basic_smoke_test_production.txt --base_url=https://myabf.com.au