#!/bin/sh

# about: count lines of code in this branch. Use --html to get output as an HTML table

HTML=$1

# Total size of Cobalt - lines of code
TOTAL=$(git ls-files | grep -Ev 'static|_build|.xml' | xargs wc -l | tail -1 | awk '{print $1}')

# print header
if [ "$HTML" = "--html" ]; then
  echo "<table class='table table-hover table-bordered'>"
  echo "<thead><tr><th>Application<th class='text-end'>Models<th class='text-end'>Functions<th class='text-end'>Templates<th class='text-end'>Lines of Code<th class='text-end'>Percentage<td></tr></thead>"
  echo "<tbody>"

else
  echo ""
  echo "Application         Models  Functions  Templates  Lines of Code  Percentage"
  echo "===========         ======  =========  =========  =============  =========="
fi

# go through dirs (some excluded) and get size of each cobalt app
for DIR in $(ls -d */ | grep -Ev 'static|docs|media|htmlcov|__pycache__')
do
  cd "$DIR"
  NAME=$(echo $DIR | cut -d "/" -f1)
  APP=$(git ls-files | grep -Ev 'static|_build|.xml' | xargs wc -l | tail -1 | awk '{print $1}')
  FUNCS=$(grep -r --include "*.py" "^def " . | grep -v migrations | wc | awk '{print $1}')
  MODELS=$(grep -r --include "models.py" "^class" . | wc | awk '{print $1}')
  TEMPLATES=$(find . -name "*.html" | grep template | wc | awk '{print $1}')
  APP_FMT=$(printf "%'d\n" $APP)
  PERCENT=$(echo "scale=0; 100 * $APP / $TOTAL" | bc)

  if [ "$HTML" = "--html" ]; then
    echo "<tr><td>$NAME<td class='text-end'>$MODELS<td class='text-end'>$FUNCS<td class='text-end'>$TEMPLATES<td class='text-end'>$APP_FMT<td class='text-end'>$PERCENT<td>"

  else

  printf '%-20s' "$NAME"
  printf '%6s' "$MODELS"
  printf '%11s' "$FUNCS"
  printf '%11s' "$TEMPLATES"
  printf '%15s' "$APP_FMT"
  printf '%11s%%' "$PERCENT"
  printf "  "

  fi

# print * for every percentage
  for i in $(seq $PERCENT); do
    if [ $PERCENT -gt 0 ]; then
       printf "*"
    fi
  done

    if [ "$HTML" = "--html" ]; then
      echo "</tr>"
    fi

  echo ""
  cd ..
done

if [ "$HTML" = "--html" ]; then
  printf "<tr><td colspan='7'><b>Total Lines of Code: %'d</tr>" $TOTAL
else
printf "\nTotal %'d lines of code\n" $TOTAL
fi

# Get total size - ignore .git dir, but we don't ignore all of the .gitignore stuff - approx value
DIR_SIZE=$(du -hs -I .git | awk '{print $1}')

if [ "$HTML" = "--html" ]; then
    echo "</table>"
else
  echo "Total directory size: $DIR_SIZE"
fi