#!/bin/bash

# about: deploy this branch to an environment

# Sometimes you want to deploy code without going through proper cgit processes
# This does it so that at least the proper label is applied

BRANCH=`git branch --show-current`

  if [ $# -ne 1 ];then
    echo ""
    echo ""
    echo "Usage: $0 env"
    echo "e.g. $0 cobalt-test-black"
   exit 1
  fi

if [[ -z $(git status -s) ]]
then

    # Get number of EC2 instances running. We want at least 2
    utils/cgit/_cgit_scale_environment_for_deployment $1
    ec2_instances=$?

  echo "Original instance number was $ec2_instances"

   DATE=$(date '+%a_%d/%m/%Y_%H:%M:%S')
   echo "Running eb deploy -m '$BRANCH@$DATE' $1"
   eb deploy -m "$BRANCH@$DATE" $1

   if [ "$ec2_instances" = "1" ]
    then

  echo "Restoring instance number to $ec2_instances. Could take a few minutes..."

   eb scale "$ec2_instances" "$1"

   fi

else
  echo ""
  echo ""
  echo "There are uncommitted changes or other problems with your git status. See below."
  echo ""
  echo ""
  git status
  echo ""
  echo ""
fi