#!/bin/bash

# Run unit and integration tests and produce coverage report

# reset coverage
coverage erase

# pass 2 parameters to get the coverage output
cgit_dev_test_unit with coverage

# pass 2 parameters to get the coverage output
cgit_dev_test_integration with coverage
coverage combine
coverage html
open htmlcov/index.html
coverage erase