#!/usr/bin/env python

# about: Editor for template comments

import PySimpleGUI as sg
from tkinter import Tk


def format_comment(lines):
    """takes in the lines from the GUI and formats as comments"""

    output = ""

    # Calculate length of the biggest line
    max_len = 70
    for line in lines:
        this_len = len(line)
        if this_len > max_len:
            max_len = this_len

    # Create top and bottom line
    filler = "".join("-" for _ in range(max_len))
    outside_line = f"{{#-{filler}-#}}\n"

    # Add top lines
    output += outside_line
    output += f"{{# {' ': <{max_len}} #}}\n"

    # fill in middle bit
    for line in lines:
        output += f"{{# {line: <{max_len}} #}}\n"

    # Blank line
    output += f"{{# {' ': <{max_len}} #}}\n"

    # How to edit line
    line = " You can edit this with cgit_util_doc_editor "
    output += f"{{# {line: <{max_len}} #}}\n"

    # Add bottom lines
    output += f"{{# {' ': <{max_len}} #}}\n"
    output += outside_line

    return output


def main():
    """Main function"""

    # Theme
    sg.theme("DarkBlue10")

    # Screen layout
    layout = [
        [sg.Text("Enter comments to format", font="Verdana 16 bold")],
        [sg.Multiline(size=(80, 40), font="Verdana 16")],
        [
            sg.Button("Copy", font="Verdana 16 bold"),
            sg.Button("Exit", font="Verdana 16 bold"),
        ],
    ]

    # Create window
    window = sg.Window("Template Doco Generator", layout, icon="docs/images/cobalt.ico")

    # Main loop
    while True:
        event, values = window.read()
        if event in [sg.WIN_CLOSED, "Cancel"]:
            break

        # build formatted output
        lines = values[0].split("\n")
        output = format_comment(lines)

        # Use tkinter to copy to clipboard
        r = Tk()
        r.withdraw()
        r.clipboard_clear()
        r.clipboard_append(output)
        r.update()  # now it stays on the clipboard after the window is closed
        r.destroy()

    window.close()


if __name__ == "__main__":
    main()
