#!/bin/sh

# about: count lines of code in this branch

# Total size of Cobalt - lines of code
TOTAL=$(git ls-files | grep -Ev 'static|_build' | xargs wc -l | tail -1 | awk '{print $1}')

# print header
echo ""
echo "Application         Models  Functions  Lines of Code  Percentage"
echo "===========         ======  =========  =============  =========="

# go through dirs (some excluded) and get size of each cobalt app
for DIR in $(ls -d */ | grep -Ev 'static|docs|media|htmlcov|__pycache__')
do
  cd "$DIR"
  NAME=$(echo $DIR | cut -d "/" -f1)
  APP=$(git ls-files | grep -Ev 'static|_build' | xargs wc -l | tail -1 | awk '{print $1}')
  FUNCS=$(grep -r --include "*.py" "^def " . | grep -v migrations | wc | awk '{print $1}')
  MODELS=$(grep -r --include "models.py" "^class" . | wc | awk '{print $1}')
  APP_FMT=$(printf "%'d\n" $APP)
  PERCENT=$(echo "scale=0; 100 * $APP / $TOTAL" | bc)
  printf '%-20s' "$NAME"
  printf '%6s' "$MODELS"
  printf '%11s' "$FUNCS"
  printf '%15s' "$APP_FMT"
  printf '%11s%%' "$PERCENT"
  printf "  "

# print * for every percentage
  for i in $(seq $PERCENT); do
    if [ $PERCENT -gt 0 ]; then
       printf "*"
    fi
  done

  echo ""
  cd ..
done

printf "\nTotal %'d lines of code\n" $TOTAL

# Get total size - ignore .git dir, but we don't ignore all of the .gitignore stuff - approx value
DIR_SIZE=$(du -hs -I .git | awk '{print $1}')
echo "Total directory size: $DIR_SIZE"
