#!/bin/sh

# about: things I can never remember\n

. utils/cgit/_cgit_include_vars

printf "\n\n${YELLOW}----------------------------"
printf "\nWhat Have You Forgotten Now?${NC}\n"
printf "${YELLOW}----------------------------${NC}\n\n"

PS3='Select: '
options=("Full name in a template" "JS Ready Function" "Bootstrap change text with size" "EB Memory Error" "Upgrade Chromedriver" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Full name in a template")
            printf "\nget_${BLUE}<var>${NC}_display\n\n"
            printf "e.g. ${YELLOW}{{ item.get_status_display }}${NC}\n\n"
            exit
            ;;
        "JS Ready Function")
            echo "\n{% block footer %}"
            echo "    <script>"
            echo "        \$(document).ready( function () {"
            echo " "
            echo "             <code here>"
            echo " "
            echo "        });"
            echo "    </script>"
            echo "{% endblock footer %}\n\n"
            exit
            ;;
        "Bootstrap change text with size")
            echo '{# Show this on screens smaller than md #}'
            echo '<span class="d-md-none">'
            echo '    Short Text'
            echo '</span>'
            echo ' '
            echo '{# Show this on screens md or larger #}'
            echo '<span class="d-none d-md-inline">'
            echo '    Longer Text Can Go Here'
            echo '</span>'
            exit
            ;;
        "EB Memory Error")
           echo "eb scale 2 <env>"
           echo "eb health <env> (get id of dodgy VM, wait until steady)"
           echo "unset AWS_SECRET_ACCESS_KEY; unset AWS_ACCESS_KEY_ID"
           echo "aws ec2 terminate-instances --instance-ids <id>"
           echo "eb scale 1 <env>"
           exit
           ;;
         "Upgrade Chromedriver")
           echo "brew update; brew upgrade chromedriver"
           echo "sudo xattr -d com.apple.quarantine '/opt/homebrew/bin/chromedriver'"
           exit
           ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
