#!/bin/sh

# about: start work on a hotfix using a new branch

if [ $# -ne 2 ]
  then
    echo ""
    echo ""
    echo "Usage $0 release_no hotfix_name"
    echo ""
    echo "e.g. $0 1.2.1 jira-254"
    echo ""
    echo "You can use any meaningful name for the hotfix branch provided it doesn't clash. It is only a temporary label."
    echo "We will prepend the release number to the branch so we can automate later steps."
    echo ""
    echo ""
    exit 1
fi

# Check for / in bugfix branch
ERROR=$(echo $2 | grep "/")
if [ -n "$ERROR" ]
then
  echo "Invalid character / in bugfix_name"
  echo ""
  exit 1
fi

echo ""
echo "Hotfix branch will be: $1=HOTFIX=$2"
echo ""
echo ""
git checkout release/$1
if [ $? -ne 0 ];then
  exit 1
fi

git pull origin release/$1
if [ $? -ne 0 ];then
  exit 1
fi


git checkout -b $1=HOTFIX=$2
