#!/bin/bash

RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Compare 2 branches
OLD=$1
NEW=$2

if [[ -z $(git status -s) ]]
then
  # Nothing
  echo ""
else
  printf "\n\n${BLUE}WARNING!!!${NC}: ${RED}Unsaved changes in current branch.${NC} These won't be included.\n\n"
  git status
  read -p "Press key to continue..." -n1 -s
fi

# Format the HTML Template
cp utils/cgit/tools/cgit_template.html /tmp/temp.html
sed -i -e "s/!!BRANCH!!/$OLD/g" /tmp/temp.html
sed -i -e "s/!!OTHERBRANCH!!/$NEW/g" /tmp/temp.html

# Now run the diff
git diff -w $NEW $OLD | diff2html -i stdin -s side --su open --htmlWrapperTemplate /tmp/temp.html