#!/bin/bash

# Silently run tests

PORT=8888
export RDS_DB_NAME=test_silent

# Kill manage.py if running
lsof -i tcp:$PORT | awk 'NR!=1 {print $2}' | xargs kill

# Kill stripe if running
pkill -TERM -f stripe

# Kill old chromedrivers
pkill -TERM -f chromedriver

# Rebuild database
cgit_dev_test_reload_db $RDS_DB_NAME
#cat << EOF > /tmp/drop_db
#\c postgres
#drop database IF EXISTS $RDS_DB_NAME;
#create database $RDS_DB_NAME with owner cobalt;
#EOF

#psql test </tmp/drop_db
#psql test < ~/test.db >/dev/null



# Start background processes
./manage.py runserver 0.0.0.0:$PORT --noreload &
stripe listen --forward-to 127.0.0.1:$PORT/payments/stripe-webhook &

# Wait for port to be open
echo "Waiting for Webserver to start..."
while ! nc -z 127.0.0.1 $PORT; do
  sleep 0.1
done
echo "Starting..."

./manage.py run_tests_silent

# Stop the django server
lsof -i tcp:$PORT | awk 'NR!=1 {print $2}' | xargs kill -SIGINT