#!/bin/bash

# Full rebuild of the test database

# Variables
export RDS_DB_NAME=test
export DUMMY_DATA_COUNT=1

# Override the DB Name if passed as a parameter
if [ $# -eq 1 ]; then
  export RDS_DB_NAME=$1
fi

# Rebuild database
cat << EOF > /tmp/drop_db
\c postgres
drop database IF EXISTS $RDS_DB_NAME;
create database $RDS_DB_NAME with owner cobalt;
EOF

psql </tmp/drop_db

utils/aws/rebuild_test_database_subcommands.sh

# Dump database for quick access
pg_dump test > ~/test.db