#!/bin/bash

# Compare current branch with a released branch

if [ $# -ne 1 ];then
  echo ""
  echo "Usage: $0 environment [test|uat|production]"
  echo ""
 exit 1
fi

BRANCH=$(git branch --show-current)

echo "You are on branch $BRANCH"
echo ""

OLD_BRANCH=$(cgit_util_branch_for_environment $1 | tail -1)

if [ $? -eq 0 ]
then
  cgit_compare "$BRANCH" "$OLD_BRANCH"
fi