#!/bin/bash

# Run unit tests

# Variables
export RDS_DB_NAME=test

echo "#########################################################################"
echo "#                                                                       #"
echo "# Reloading cached database...                                          #"
echo "#                                                                       #"
echo "# If you have changed models or static data config then you should      #"
echo "# run cgit_dev_test_reload_db first, to update the cached version.      #"
echo "#                                                                       #"
echo "# Apologies for the mess below, that is pytest.                         #"
echo "#                                                                       #"
echo "#########################################################################"

# Rebuild database
cat << EOF > /tmp/drop_db
\c postgres
drop database IF EXISTS $RDS_DB_NAME;
create database $RDS_DB_NAME with owner cobalt;
EOF

psql </tmp/drop_db

psql test < ~/test.db >/dev/null

echo "#########################################################################"
echo "#                                                                       #"
echo "# Here comes pytest (or is it pytest-django?). Hold on...               #"
echo "#                                                                       #"
echo "#########################################################################"

pytest --html=/tmp/pytest-report.html --self-contained-html --import-mode=importlib

echo "#########################################################################"
echo "#                                                                       #"
echo "# Opening pytest-html report...                                         #"
echo "#                                                                       #"
echo "#########################################################################"

open /tmp/pytest-report.html