#!/bin/bash

# Run integration tests
# Call with 1 parameter to show the web browser
# Call with 2 parameters to generate coverage data

# Variables
PORT=8088
export RDS_DB_NAME=test
export DUMMY_DATA_COUNT=1

# Kill manage.py if running
lsof -i tcp:$PORT | awk 'NR!=1 {print $2}' | xargs kill

# Kill stripe if running
pkill -TERM -f stripe

# Kill old chromedrivers
pkill -TERM -f chromedriver

# Rebuild database
cat << EOF > /tmp/drop_db
\c postgres
drop database IF EXISTS $RDS_DB_NAME;
create database $RDS_DB_NAME with owner cobalt;
EOF

psql </tmp/drop_db
psql test < ~/test.db >/dev/null

open . ~/Development/c2/cobalt/utils/cgit/tools/test_manage_short.terminal
open . ~/Development/c2/cobalt/utils/cgit/tools/test_stripe_short.terminal

sleep 3
echo "Starting..."

# Call with 1 parameter to show the web browser
# Call with 2 parameters to generate coverage data
if [ $# -eq 2 ]
  then
  coverage run -p ./manage.py run_tests_integration --base_url http://127.0.0.1:$PORT --headless true
elif [ $# eq 1 ]
  then
  ./manage.py run_tests_integration --base_url http://127.0.0.1:$PORT
  else
  ./manage.py run_tests_integration --base_url http://127.0.0.1:$PORT --headless true
fi

# Stop the django server
lsof -i tcp:$PORT | awk 'NR!=1 {print $2}' | xargs kill -SIGINT