# Generated by Django 3.2.15 on 2023-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="XeroCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorisation_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
                ("expires", models.DateTimeField(null=True)),
                (
                    "refresh_token",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tenant_id", models.CharField(blank=True, default="", max_length=100)),
            ],
        ),
    ]
