# Generated by Django 2.1 on 2020-03-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="dob", field=models.DateField(null=True),
        ),
    ]
