# Generated by Django 2.1 on 2020-04-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_bbo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank="True", null=True),
        ),
    ]
