# Generated by Django 2.1 on 2020-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20200415_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pic",
            field=models.ImageField(
                default="pic_folder/default-avatar.png", upload_to="pic_folder/"
            ),
        ),
    ]
