# Generated by Django 2.1 on 2020-05-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auto_20200505_1404"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="autotopup_amount",),
    ]
