# Generated by Django 2.2.12 on 2020-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_auto_20200521_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_facts",
            field=models.BooleanField(default=True),
        ),
    ]
