# Generated by Django 2.2.12 on 2020-05-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_user_show_facts"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="show_facts",),
    ]
