# Generated by Django 3.0.8 on 2020-07-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_user_show_facts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="stripe_auto_confirmed",
            field=models.CharField(
                choices=[("Off", "Off"), ("Pending", "Pending"), ("On", "On")],
                default="Off",
                max_length=9,
                verbose_name="Stripe Auto Confirmed",
            ),
        ),
    ]
