# Generated by Django 2.2.13 on 2020-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_auto_20200722_1003"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_abf_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Receive ABF Newsletter"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_marketing",
            field=models.BooleanField(default=True, verbose_name="Receive Marketing"),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_monthly_masterpoints_report",
            field=models.BooleanField(
                default=True, verbose_name="Receive Monthly Masterpoints Report"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_payments_emails",
            field=models.BooleanField(
                default=True, verbose_name="Receive Payments Emails"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_sms_reminders",
            field=models.BooleanField(
                default=False, verbose_name="Receive SMS Reminders"
            ),
        ),
    ]
