# Generated by Django 3.0.9 on 2020-09-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_auto_20200901_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(blank="True", null=True),
        ),
    ]
