# Generated by Django 3.0.9 on 2020-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_user_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="system_number_search",
            field=models.BooleanField(
                default=True, verbose_name="Show ABF number on searches"
            ),
        ),
    ]
