# Generated by Django 3.0.9 on 2021-01-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_user_windows_scrollbar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="windows_scrollbar",
            field=models.BooleanField(
                default=False, verbose_name="Use Perfect Scrollbar on Windows"
            ),
        ),
    ]
