# Generated by Django 3.0.9 on 2021-04-09 10:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210104_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank='True', null=True, validators=[accounts.models.no_future]),
        ),
    ]
