# Generated by Django 3.2.4 on 2021-08-13 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0018_auto_20210813_2216"),
        ("accounts", "0032_alter_user_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnregisteredUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "system_number",
                    models.IntegerField(unique=True, verbose_name="ABF Number"),
                ),
                (
                    "last_registration_invite_sent",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Last Registration Invite Sent",
                    ),
                ),
                (
                    "last_registration_invite_by_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "last_registration_invite_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
