# Generated by Django 3.2.4 on 2021-08-13 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0021_membermembershiptype_system_number"),
        ("accounts", "0033_unregistereduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unregistereduser",
            name="last_registration_invite_by_club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="unregistereduser",
            name="last_registration_invite_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
