# Generated by Django 3.2.4 on 2021-08-13 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_auto_20210813_2253"),
    ]

    operations = [
        migrations.AddField(
            model_name="unregistereduser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unregistereduser",
            name="last_updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="last_updated",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unregistereduser",
            name="origin",
            field=models.CharField(
                choices=[
                    ("MPC", "Masterpoints Centre Import"),
                    ("Pianola", "Pianola Import"),
                    ("Manual", "Manual Entry"),
                ],
                default="Manual",
                max_length=10,
                verbose_name="Origin",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unregistereduser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="unregistereduser",
            name="system_number",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ABF Number"
            ),
        ),
    ]
