# Generated by Django 3.2.4 on 2021-08-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_auto_20210814_0747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="system_number",
            field=models.IntegerField(
                blank=True, db_index=True, unique=True, verbose_name="ABF Number"
            ),
        ),
    ]
