# Generated by Django 3.2.4 on 2021-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_auto_20210826_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unregistereduser",
            name="first_name",
            field=models.CharField(
                default="unset", max_length=150, verbose_name="First Name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unregistereduser",
            name="last_name",
            field=models.CharField(
                default="unset", max_length=150, verbose_name="Last Name"
            ),
            preserve_default=False,
        ),
    ]
