# Generated by Django 3.2.4 on 2021-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_auto_20210903_1144"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_covid_confirm",
            field=models.BooleanField(default=False, verbose_name="Covid Vaccinated"),
        ),
    ]
