# Generated by Django 3.2.4 on 2021-09-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_user_user_covid_confirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_covid_confirm",
            field=models.BooleanField(
                default=False, verbose_name="Certificate Confirmed by Administrator"
            ),
        ),
    ]
