# Generated by Django 3.2.4 on 2021-09-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_auto_20210930_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="covid_status",
            field=models.CharField(
                choices=[
                    ("US", "Unset"),
                    ("UC", "User Confirmed"),
                    ("AC", "Administrator Confirmed"),
                    ("AV", "User Medically Exempt from Vaccination"),
                ],
                default="US",
                max_length=2,
            ),
        ),
    ]
