# Generated by Django 3.2.10 on 2021-12-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_apitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default="API_vBgeB-vcry/WrD{o^\\61Z}(dsNLi\\io8[8w7", max_length=40
            ),
        ),
    ]
