# Generated by Django 3.2.10 on 2021-12-14 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_auto_20211210_0656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default="API_oO7f4U}QNoq_JSbP[kBL(0SP$Ts6dy^GJBmm", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="We only accept Australian phone numbers starting 04 which are 10 numbers long.",
                        regex="^04\\d{8}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="receive_sms_results",
            field=models.BooleanField(default=True, verbose_name="Receive SMS Results"),
        ),
    ]
