# Generated by Django 3.2.10 on 2021-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_auto_20211214_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default="API_YR}yWmrplNZ5vjcOTPp!Ltb86blZHXbLe919", max_length=40
            ),
        ),
    ]
