# Generated by Django 3.2.10 on 2021-12-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_alter_apitoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="token",
            field=models.CharField(
                default="API_30mfHK$pX$NNS_cr{w]k[|QzVtR0OIcPjWJi", max_length=40
            ),
        ),
    ]
