# Generated by Django 3.2.10 on 2022-01-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_useradditionalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionalinfo",
            name="email_hard_bounce_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
