# Generated by Django 3.2.13 on 2022-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_useradditionalinfo_email_hard_bounce_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="unregistereduser",
            name="email_hard_bounce",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unregistereduser",
            name="email_hard_bounce_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unregistereduser",
            name="email_hard_bounce_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
