# Generated by Django 3.2.10 on 2022-10-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_auto_20220620_2209"),
    ]

    operations = [
        migrations.AddField(
            model_name="unregistereduser",
            name="identifier",
            field=models.CharField(default="UNSET", max_length=10),
        ),
    ]
