# Generated by Django 3.2.15 on 2022-10-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_unregistereduser_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unregistereduser",
            name="identifier",
            field=models.CharField(default="NOTSET", max_length=10),
        ),
    ]
