# Generated by Django 3.2.15 on 2022-10-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_unregistereduser_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unregistereduser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="unregistereduser",
            name="email_hard_bounce",
        ),
        migrations.RemoveField(
            model_name="unregistereduser",
            name="email_hard_bounce_date",
        ),
        migrations.RemoveField(
            model_name="unregistereduser",
            name="email_hard_bounce_reason",
        ),
    ]
