# Generated by Django 3.2.15 on 2023-03-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_systemcard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemCard",
        ),
    ]
