# Generated by Django 3.2.15 on 2023-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_systemcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemcard",
            name="save_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_1c",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_1d",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_1h",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_1nt",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_1s",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_2c",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_2d",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_2h",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_2nt",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="opening_2s",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="player1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="player2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="summary_bidding",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="systemcard",
            name="summary_carding",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
