# Generated by Django 3.2.15 on 2023-03-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_alter_systemcard_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="systemcard",
            unique_together=set(),
        ),
    ]
