# Generated by Django 3.2.15 on 2023-03-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_alter_systemcard_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_low_balance_emails",
            field=models.BooleanField(default=True),
        ),
    ]
