# Generated by Django 3.2.15 on 2023-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_user_receive_low_balance_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionalinfo",
            name="congress_view_filters",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
