# Generated by Django 3.2.15 on 2023-04-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_useradditionalinfo_congress_view_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionalinfo",
            name="last_club_visited",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
