# Generated by Django 3.2.19 on 2024-07-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0066_useradditionalinfo_last_club_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="unregistereduser",
            name="deceased",
            field=models.BooleanField(default=False, verbose_name="Deceased"),
        ),
        migrations.AddField(
            model_name="user",
            name="deceased",
            field=models.BooleanField(default=False, verbose_name="Deceased"),
        ),
        migrations.AddField(
            model_name="user",
            name="share_with_clubs",
            field=models.BooleanField(
                default=False, verbose_name="Share details with clubs"
            ),
        ),
    ]
