# Generated by Django 3.2.19 on 2024-07-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0067_auto_20240722_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradditionalinfo",
            name="member_sort_order",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
