# Generated by Django 3.2.19 on 2024-08-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_alter_unregistereduser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="share_with_clubs",
        ),
    ]
