# Generated by Django 3.2.4 on 2021-06-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_auto_20210628_1000"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="title",
            field=models.CharField(default="Unset", max_length=80),
            preserve_default=False,
        ),
    ]
