# Generated by Django 3.2.4 on 2021-06-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_incident_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="reported_by_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
