# Generated by Django 3.2.4 on 2021-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0005_auto_20210628_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="reported_by_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
