# Generated by Django 3.2.4 on 2021-06-29 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_incident_reported_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Congress Admin', 'Congress Admin'), ('Congress Entry', 'Congress Entry'), ('Club Admin', 'Club Admin'), ('Forums', 'Forums'), ('Masterpoints', 'Masterpoints'), ('Notifications', 'Notifications'), ('Other', 'Other'), ('Payments', 'Payments'), ('Profile/Settings', 'Profile/Settings'), ('Registration', 'Registration'), ('Security', 'Security')], default='Other', max_length=30),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='bulletins/%Y/%m/%d/')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.incident')),
            ],
        ),
    ]
