# Generated by Django 3.2.4 on 2021-06-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_auto_20210630_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='helpdesk/%Y/%m/%d/'),
        ),
    ]
