# Generated by Django 3.2.4 on 2021-06-30 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0008_alter_attachment_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotifyUserByType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("Congress Admin", "Congress Admin"),
                            ("Congress Entry", "Congress Entry"),
                            ("Club Admin", "Club Admin"),
                            ("Forums", "Forums"),
                            ("Masterpoints", "Masterpoints"),
                            ("Notifications", "Notifications"),
                            ("Other", "Other"),
                            ("Payments", "Payments"),
                            ("Profile/Settings", "Profile/Settings"),
                            ("Registration", "Registration"),
                            ("Security", "Security"),
                            ("All", "All"),
                        ],
                        default="All",
                        max_length=30,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
