# Generated by Django 3.2.4 on 2021-07-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0010_alter_incident_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("Bridge Credits", "Bridge Credits"),
                    ("Congress Admin", "Congress Admin"),
                    ("Congress Entry", "Congress Entry"),
                    ("Club Admin", "Club Admin"),
                    ("Forums", "Forums"),
                    ("Masterpoints", "Masterpoints"),
                    ("Notifications", "Notifications"),
                    ("Other", "Other"),
                    ("Payments", "Payments"),
                    ("Profile/Settings", "Profile/Settings"),
                    ("Registration", "Registration"),
                    ("Security", "Security"),
                ],
                default="Other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="reported_by_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.CharField(
                choices=[
                    ("Critical", "Critical"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                default="Medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notifyuserbytype",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("Bridge Credits", "Bridge Credits"),
                    ("Congress Admin", "Congress Admin"),
                    ("Congress Entry", "Congress Entry"),
                    ("Club Admin", "Club Admin"),
                    ("Forums", "Forums"),
                    ("Masterpoints", "Masterpoints"),
                    ("Notifications", "Notifications"),
                    ("Other", "Other"),
                    ("Payments", "Payments"),
                    ("Profile/Settings", "Profile/Settings"),
                    ("Registration", "Registration"),
                    ("Security", "Security"),
                    ("All", "All"),
                ],
                default="All",
                max_length=30,
            ),
        ),
    ]
