# Generated by Django 3.2.4 on 2021-07-09 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support", "0011_auto_20210707_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.user",
            ),
            preserve_default=False,
        ),
    ]
