# Generated by Django 3.2.4 on 2021-08-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0012_attachment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("Bridge Credits", "Bridge Credits"),
                    ("Congress Admin", "Congress Admin"),
                    ("Congress Entry", "Congress Entry"),
                    ("Club Admin", "Club Admin"),
                    ("Forums", "Forums"),
                    ("Masterpoints", "Masterpoints"),
                    ("Notifications", "Notifications"),
                    ("Other", "Other"),
                    ("Payments/Refunds", "Payments/Refunds"),
                    ("Profile/Settings", "Profile/Settings"),
                    ("Registration", "Registration"),
                    ("Security", "Security"),
                ],
                default="Other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notifyuserbytype",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("Bridge Credits", "Bridge Credits"),
                    ("Congress Admin", "Congress Admin"),
                    ("Congress Entry", "Congress Entry"),
                    ("Club Admin", "Club Admin"),
                    ("Forums", "Forums"),
                    ("Masterpoints", "Masterpoints"),
                    ("Notifications", "Notifications"),
                    ("Other", "Other"),
                    ("Payments/Refunds", "Payments/Refunds"),
                    ("Profile/Settings", "Profile/Settings"),
                    ("Registration", "Registration"),
                    ("Security", "Security"),
                    ("All", "All"),
                ],
                default="All",
                max_length=30,
            ),
        ),
    ]
