#!/bin/bash
# Shows a spinner while another command is running.
# Modelled on https://unix.stackexchange.com/questions/225179/display-spinner-while-waiting-for-some-process-to-finish

function shutdown() {
  # reset cursor
  tput cnorm
}
trap shutdown EXIT

function cursorBack() {
  echo -en "\033[$1D"
}

function spinner() {
  # make sure we use non-unicode character type locale
  # (that way it works for any locale as long as the font supports the characters)
  local LC_CTYPE=C

  local pid=$1 # Process Id of the previous running command

  local spin='-\|/'
  local char_width=1
#  local spin='⣾⣽⣻⢿⡿⣟⣯⣷'
#  local char_width=3

  local i=0
  tput civis # cursor invisible
  while kill -0 "$pid" 2>/dev/null; do
    local i=$(((i + $char_width) % ${#spin}))
    printf "%s" "${spin:$i:$char_width}"

    cursorBack 1
    sleep .1
  done

  echo " "
  tput cnorm
  wait "$pid" # capture exit code
  return $?
}

("$@") &

spinner $!