""" Generated by utils/cgit/cgit_util_generate_admin_file on 2022-01-24 14:26:19.559531 """

from django.contrib import admin
from .models import (
    Forum,
    Post,
    Comment1,
    Comment2,
    LikePost,
    LikeComment1,
    LikeComment2,
    ForumFollow,
)


class ForumAdmin(admin.ModelAdmin):
    """Admin class for model Forum"""

    search_fields = ["title"]


class PostAdmin(admin.ModelAdmin):
    """Admin class for model Post"""

    search_fields = ["author"]
    autocomplete_fields = [
        "forum",
    ]


class Comment1Admin(admin.ModelAdmin):
    """Admin class for model Comment1"""

    search_fields = ["author"]
    autocomplete_fields = [
        "post",
    ]


class Comment2Admin(admin.ModelAdmin):
    """Admin class for model Comment2"""

    search_fields = ["author"]
    autocomplete_fields = [
        "post",
        "comment1",
    ]


class LikePostAdmin(admin.ModelAdmin):
    """Admin class for model LikePost"""

    autocomplete_fields = [
        "post",
    ]


class LikeComment1Admin(admin.ModelAdmin):
    """Admin class for model LikeComment1"""

    autocomplete_fields = [
        "comment1",
    ]


class LikeComment2Admin(admin.ModelAdmin):
    """Admin class for model LikeComment2"""

    autocomplete_fields = [
        "comment2",
    ]


class ForumFollowAdmin(admin.ModelAdmin):
    """Admin class for model ForumFollow"""

    autocomplete_fields = [
        "user",
        "forum",
    ]


admin.site.register(Forum, ForumAdmin)
admin.site.register(Post, PostAdmin)
admin.site.register(Comment1, Comment1Admin)
admin.site.register(Comment2, Comment2Admin)
admin.site.register(LikePost, LikePostAdmin)
admin.site.register(LikeComment1, LikeComment1Admin)
admin.site.register(LikeComment2, LikeComment2Admin)
admin.site.register(ForumFollow, ForumFollowAdmin)
