# Generated by Django 2.1 on 2020-03-30 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LikeComment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeComment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='comment1',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment2',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='comment1',
            name='last_change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment2',
            name='last_change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='likecomment2',
            name='comment2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Comment2'),
        ),
        migrations.AddField(
            model_name='likecomment2',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecomment1',
            name='comment1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.Comment1'),
        ),
        migrations.AddField(
            model_name='likecomment1',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='forums.Forum'),
            preserve_default=False,
        ),
    ]
