# Generated by Django 2.1.5 on 2020-04-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0002_auto_20200331_0702"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(default="unset"),
            preserve_default=False,
        ),
    ]
