# Generated by Django 2.1.5 on 2020-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0004_comment2_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
