# Generated by Django 2.1 on 2020-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0005_post_comments_allowed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="description",
            field=models.CharField(max_length=200, verbose_name="Forum Description"),
        ),
        migrations.AlterField(
            model_name="forum",
            name="title",
            field=models.CharField(max_length=80, verbose_name="Forum Short Title"),
        ),
    ]
