# Generated by Django 2.2.13 on 2020-06-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0007_userforumrole"),
    ]

    operations = [
        migrations.DeleteModel(name="UserForumRole",),
    ]
