# Generated by Django 2.2.12 on 2020-06-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0008_delete_userforumrole"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="comments_allowed",),
    ]
