# Generated by Django 3.0.8 on 2020-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0011_auto_20200623_1621"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="summary",),
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
