# Generated by Django 3.0.8 on 2020-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0014_forum_forum_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="bg_colour",
            field=models.CharField(
                default="white", max_length=20, verbose_name="Background Colour"
            ),
        ),
        migrations.AddField(
            model_name="forum",
            name="fg_colour",
            field=models.CharField(
                default="black", max_length=20, verbose_name="Background Colour"
            ),
        ),
    ]
