# Generated by Django 3.0.8 on 2020-07-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forums", "0015_auto_20200713_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="fg_colour",
            field=models.CharField(
                default="black", max_length=20, verbose_name="Foreground Colour"
            ),
        ),
    ]
