from django.urls import path

import club_sessions.views.imports
import club_sessions.views.manage_session
import club_sessions.views.new_session
from club_sessions.views import reports

app_name = "club_sessions"  # pylint: disable=invalid-name

urlpatterns = [
    path(
        "new-session/<int:club_id>",
        club_sessions.views.new_session.new_session,
        name="new_session",
    ),
    path(
        "session/<int:session_id>",
        club_sessions.views.manage_session.manage_session,
        name="manage_session",
    ),
    path(
        "session",
        club_sessions.views.manage_session.manage_session,
        name="manage_session_no_id",
    ),
    path(
        "session/settings",
        club_sessions.views.manage_session.tab_settings_htmx,
        name="tab_settings_htmx",
    ),
    path(
        "session/uploads-file",
        club_sessions.views.imports.import_file_upload_htmx,
        name="session_import_file_upload_htmx",
    ),
    path(
        "session/details",
        club_sessions.views.manage_session.tab_session_htmx,
        name="tab_session_htmx",
    ),
    path(
        "session/edit-session-entry",
        club_sessions.views.manage_session.edit_session_entry_htmx,
        name="edit_session_entry_htmx",
    ),
    path(
        "session/edit-session-entry-extras",
        club_sessions.views.manage_session.edit_session_entry_extras_htmx,
        name="edit_session_entry_extras_htmx",
    ),
    path(
        "session/edit-session-entry-change-payment-method",
        club_sessions.views.manage_session.change_payment_method_htmx,
        name="session_entry_change_payment_method_htmx",
    ),
    path(
        "session/edit-session-entry-change-paid-amount",
        club_sessions.views.manage_session.change_paid_amount_status_htmx,
        name="session_entry_change_paid_amount_htmx",
    ),
    path(
        "session/edit-session-totals",
        club_sessions.views.manage_session.session_totals_htmx,
        name="session_entry_session_totals_htmx",
    ),
    path(
        "session/add-misc-payment",
        club_sessions.views.manage_session.add_misc_payment_htmx,
        name="session_add_misc_payment_htmx",
    ),
    path(
        "session/process-bridge-credits",
        club_sessions.views.manage_session.process_bridge_credits_htmx,
        name="process_bridge_credits_htmx",
    ),
    path(
        "session/process-off-system-payments",
        club_sessions.views.manage_session.process_off_system_payments_htmx,
        name="process_off_system_payments_htmx",
    ),
    path(
        "session/delete-misc-session-payment",
        club_sessions.views.manage_session.delete_misc_session_payment_htmx,
        name="delete_misc_session_payment_htmx",
    ),
    path(
        "session/toggle-paid-misc-session-payment",
        club_sessions.views.manage_session.toggle_paid_misc_session_payment_htmx,
        name="toggle_paid_misc_session_payment_htmx",
    ),
    path(
        "session/add-table",
        club_sessions.views.manage_session.add_table_htmx,
        name="add_table_htmx",
    ),
    path(
        "session/delete-table",
        club_sessions.views.manage_session.delete_table_htmx,
        name="delete_table_htmx",
    ),
    path(
        "reports/reconciliation",
        reports.reconciliation_htmx,
        name="reports_reconciliation_htmx",
    ),
    path(
        "reports/import-messages",
        reports.import_messages_htmx,
        name="reports_import_messages_htmx",
    ),
    path(
        "reports/csv-download/<int:session_id>",
        reports.csv_download,
        name="reports_csv_download",
    ),
    path(
        "reports/low-balance",
        reports.low_balance_report_htmx,
        name="reports_low_balance_report_htmx",
    ),
    path(
        "member/top-up",
        club_sessions.views.manage_session.top_up_member_htmx,
        name="session_top_up_member_htmx",
    ),
    path(
        "edit/change-player",
        club_sessions.views.manage_session.change_player_htmx,
        name="session_change_player_htmx",
    ),
    path(
        "edit/get-fee-for-payment-method",
        club_sessions.views.manage_session.get_fee_for_payment_method_htmx,
        name="get_fee_for_payment_method_htmx",
    ),
    path(
        "totals/predict-bridge-credits-failures",
        club_sessions.views.manage_session.predict_bridge_credits_failures_htmx,
        name="predict_bridge_credits_failures_htmx",
    ),
]
