# Generated by Django 3.2.5 on 2021-10-08 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="SessionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair_team_number", models.IntegerField()),
                (
                    "seat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "North"),
                            ("S", "South"),
                            ("E", "East"),
                            ("W", "West"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SessionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "master_session_type",
                    models.CharField(
                        choices=[("DP", "Duplicate"), ("MS", "Multi-session")],
                        default="DP",
                        max_length=2,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SessionTypePaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
