# Generated by Django 3.2.5 on 2021-10-08 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("club_sessions", "0001_initial"),
        ("organisations", "0034_organisationfrontpage"),
        ("payments", "0063_orgpaymentmethod_userpendingpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontypepaymentmethod",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.orgpaymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="sessiontypepaymentmethod",
            name="session_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="club_sessions.sessiontype",
            ),
        ),
        migrations.AddField(
            model_name="sessiontype",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="member_tran",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.membertransaction",
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="org_tran",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.organisationtransaction",
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.orgpaymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="club_sessions.session"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="session_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="club_sessions.sessiontype",
            ),
        ),
    ]
