# Generated by Django 3.2.5 on 2021-10-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontype",
            name="name",
            field=models.CharField(default="Unset", max_length=15),
            preserve_default=False,
        ),
    ]
