# Generated by Django 3.2.5 on 2021-10-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0003_sessiontype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionentry",
            options={"verbose_name_plural": "Session entries"},
        ),
    ]
