# Generated by Django 3.2.5 on 2021-10-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0005_alter_sessiontype_master_session_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontypepaymentmethod",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
