# Generated by Django 3.2.5 on 2021-10-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0036_rename_miscpaytypes_miscpaytype"),
        ("club_sessions", "0006_sessiontypepaymentmethod_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessiontypepaymentmethod",
            name="fee",
        ),
        migrations.CreateModel(
            name="SessionTypePaymentMethodMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.membershiptype",
                    ),
                ),
                (
                    "session_type_payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="club_sessions.sessiontypepaymentmethod",
                    ),
                ),
            ],
        ),
    ]
