# Generated by Django 3.2.5 on 2021-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0010_auto_20211102_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('EV', 'Evening'), ('AL', 'All Day')], max_length=2, null=True),
        ),
    ]
