# Generated by Django 3.2.5 on 2021-11-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_sessions', '0011_alter_session_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_of_day',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('EV', 'Evening'), ('AL', 'All Day')], default='AM', max_length=2, null=True),
        ),
    ]
