# Generated by Django 3.2.12 on 2022-05-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0014_alter_sessionentry_payment_method"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionentry",
            unique_together={("session", "pair_team_number", "seat")},
        ),
    ]
