# Generated by Django 3.2.12 on 2022-05-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0015_alter_sessionentry_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionentry",
            old_name="player",
            new_name="system_number",
        ),
    ]
