# Generated by Django 3.2.13 on 2022-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0016_rename_player_sessionentry_system_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionentry",
            options={
                "ordering": ["pair_team_number", "seat_number_internal"],
                "verbose_name_plural": "Session entries",
            },
        ),
        migrations.AddField(
            model_name="sessionentry",
            name="seat_number_internal",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
