# Generated by Django 3.2.13 on 2022-07-19 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0055_organisation_default_secondary_payment_type"),
        ("club_sessions", "0019_sessionentry_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="additional_session_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="session",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SessionMiscPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_made", models.BooleanField(default=False)),
                (
                    "optional_description",
                    models.TextField(blank=True, max_length=50, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "misc_pay_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.miscpaytype",
                    ),
                ),
                (
                    "session_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club_sessions.sessionentry",
                    ),
                ),
            ],
        ),
    ]
