# Generated by Django 3.2.10 on 2022-07-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0069_auto_20220720_0913"),
        ("club_sessions", "0020_auto_20220720_0913"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="default_secondary_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.orgpaymentmethod",
            ),
        ),
    ]
