# Generated by Django 3.2.13 on 2022-07-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0021_session_default_secondary_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmiscpayment",
            name="misc_pay_type",
        ),
    ]
