# Generated by Django 3.2.10 on 2022-08-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0023_alter_sessiontype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="additional_session_fee_reason",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
