# Generated by Django 3.2.15 on 2022-09-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0025_session_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionentry",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sessionentry",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
