# Generated by Django 3.2.15 on 2022-09-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0026_auto_20220902_0952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="club",
        ),
    ]
