# Generated by Django 3.2.15 on 2022-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0027_remove_session_club"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("LD", "Data Loaded"),
                    ("BC", "Credits Processed"),
                    ("OS", "Off System Payments Processed"),
                    ("CO", "Complete"),
                ],
                default="LD",
                max_length=2,
            ),
        ),
    ]
