# Generated by Django 3.2.13 on 2022-09-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0028_auto_20220902_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="import_messages",
            field=models.TextField(blank=True, null=True),
        ),
    ]
