# Generated by Django 3.2.15 on 2022-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0030_alter_session_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionentry",
            name="player_name_from_file",
            field=models.TextField(default="Unknown", max_length=60),
        ),
    ]
