# Generated by Django 3.2.15 on 2022-09-19 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0069_auto_20220720_0913"),
        ("club_sessions", "0031_sessionentry_player_name_from_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionmiscpayment",
            old_name="optional_description",
            new_name="description",
        ),
        migrations.AddField(
            model_name="sessionmiscpayment",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.orgpaymentmethod",
            ),
        ),
    ]
