# Generated by Django 3.2.15 on 2022-10-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0035_session_director_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionentry",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is Processed"),
        ),
        migrations.AlterField(
            model_name="sessionmiscpayment",
            name="payment_made",
            field=models.BooleanField(default=False, verbose_name="Is Processed"),
        ),
    ]
