# Generated by Django 3.2.10 on 2022-12-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0036_auto_20221014_1316"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmiscpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("TU", "Top Up"), ("OT", "Other")], default="OT", max_length=2
            ),
        ),
    ]
