# Generated by Django 3.2.10 on 2022-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_sessions", "0037_sessionmiscpayment_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionentry",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=-99, max_digits=10),
        ),
    ]
