# Generated by Django 2.1 on 2020-05-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapplication',
            old_name='application_content_type',
            new_name='model_content_type',
        ),
        migrations.RenameField(
            model_name='userapplication',
            old_name='application_id',
            new_name='model_id',
        ),
    ]
