# Generated by Django 2.2.12 on 2020-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200529_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='rule_type',
            field=models.CharField(choices=[('Allow', 'Allow User Access'), ('Block', 'Blcok User Access')], default='Allow', max_length=5),
        ),
    ]
