# Generated by Django 2.1 on 2020-06-01 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0003_userapplication_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RBACGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('rule_type', models.CharField(choices=[('Allow', 'Allow User Access'), ('Block', 'Blcok User Access')], default='Allow', max_length=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.RBACGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RBACUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rbac_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.RBACGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='member',
        ),
        migrations.RemoveField(
            model_name='userapplication',
            name='model_content_type',
        ),
        migrations.DeleteModel(
            name='UserApplication',
        ),
    ]
