# Generated by Django 2.2.12 on 2020-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20200601_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgroup',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
