# Generated by Django 2.2.12 on 2020-06-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20200601_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgrouprole',
            name='role',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
