# Generated by Django 2.2.12 on 2020-06-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20200601_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbacgrouprole',
            name='role',
        ),
        migrations.AddField(
            model_name='rbacgrouprole',
            name='action',
            field=models.CharField(default='pass', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbacgrouprole',
            name='app',
            field=models.CharField(default='app', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbacgrouprole',
            name='model',
            field=models.CharField(default='model', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbacgrouprole',
            name='model_id',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
