# Generated by Django 2.2.12 on 2020-06-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20200602_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacgroup',
            name='description',
            field=models.CharField(default='blank', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
