# Generated by Django 2.2.12 on 2020-06-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_rbacgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgroup',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rbacgroup',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
