# Generated by Django 2.2.12 on 2020-06-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20200602_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbacusergroup',
            old_name='rbac_group',
            new_name='group',
        ),
    ]
