# Generated by Django 2.2.12 on 2020-06-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20200602_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgrouprole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_group2', to='rbac.RBACGroup'),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_group1', to='rbac.RBACGroup'),
        ),
    ]
