# Generated by Django 2.2.12 on 2020-06-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20200602_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgrouprole',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.RBACGroup'),
        ),
        migrations.AlterField(
            model_name='rbacusergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.RBACGroup'),
        ),
    ]
