# Generated by Django 2.2.12 on 2020-06-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20200602_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACModelDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('default_behaviour', models.CharField(choices=[('Allow', 'Allow User Access'), ('Block', 'Block User Access')], default='Allow', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='rbacgrouprole',
            name='rule_type',
            field=models.CharField(choices=[('Allow', 'Allow User Access'), ('Block', 'Block User Access')], default='Allow', max_length=5),
        ),
    ]
