# Generated by Django 2.2.12 on 2020-06-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_auto_20200603_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacgrouprole',
            name='model_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
