# Generated by Django 2.2.13 on 2020-06-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0020_auto_20200610_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rbacadmingroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("Forum", "Forums"),
                    ("Organisation", "Organisations"),
                    ("Payment", "Payments"),
                    ("Scoring", "Scoring"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rbacgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("Forum", "Forums"),
                    ("Organisation", "Organisations"),
                    ("Payment", "Payments"),
                    ("Scoring", "Scoring"),
                ],
                max_length=20,
            ),
        ),
    ]
