# Generated by Django 2.2.12 on 2020-06-12 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0022_auto_20200611_1502"),
    ]

    operations = [
        migrations.RemoveField(model_name="rbacadmingroup", name="group_type",),
    ]
