# Generated by Django 2.2.13 on 2020-06-16 04:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rbac", "0023_remove_rbacadmingroup_group_type"),
    ]

    operations = [
        migrations.RenameModel(old_name="RBACUserTree", new_name="RBACAdminTree",),
    ]
