# Generated by Django 2.2.13 on 2020-06-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0024_auto_20200616_1420"),
    ]

    operations = [
        migrations.RemoveField(model_name="rbacadmintree", name="member",),
        migrations.AddField(
            model_name="rbacadmintree",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rbac.RBACAdminGroup",
            ),
            preserve_default=False,
        ),
    ]
