# Generated by Django 2.2.13 on 2020-06-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0025_auto_20200625_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rbacadmingroup",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="rbacadmingroup",
            name="name_item",
            field=models.CharField(max_length=100),
        ),
    ]
