# Generated by Django 3.0.8 on 2020-07-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0026_auto_20200629_1116"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rbacgroup", unique_together={("name_qualifier", "name_item")},
        ),
    ]
