# Generated by Django 3.0.8 on 2020-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0027_auto_20200714_1454"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rbacadmintree",
            name="tree",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="rbacadmingroup", unique_together={("name_qualifier", "name_item")},
        ),
    ]
