# Generated by Django 3.0.8 on 2020-08-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0028_auto_20200714_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="rbacappmodelaction",
            name="description",
            field=models.CharField(default="TBA", max_length=80),
            preserve_default=False,
        ),
    ]
