# Generated by Django 3.0.9 on 2020-12-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0030_auto_20200807_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rbacadmingroup",
            name="description",
            field=models.TextField(),
        ),
    ]
