# Generated by Django 3.2.4 on 2021-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0031_auto_20201221_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rbacgroup",
            name="description",
            field=models.TextField(),
        ),
    ]
