# Generated by Django 3.2.10 on 2022-03-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rbac", "0032_alter_rbacgroup_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rbacappmodelaction",
            unique_together={("app", "model", "valid_action")},
        ),
    ]
