# Generated by Django 2.1 on 2020-04-28 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Club', 'Bridge Club'), ('State', 'State Association'), ('National', 'National Body'), ('Other', 'Other')], max_length=8, null=True)),
                ('address1', models.CharField(max_length=30, null=True)),
                ('address2', models.CharField(max_length=30, null=True)),
                ('address3', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=3, null=True)),
                ('postcode', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
