# Generated by Django 2.1 on 2020-04-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20200428_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='address3',
            new_name='suburb',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
