# Generated by Django 2.1 on 2020-04-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20200428_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
