# Generated by Django 3.0.8 on 2020-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0005_auto_20200502_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="bank_account",
            field=models.CharField(blank="True", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="organisation",
            name="bank_bsb",
            field=models.CharField(blank="True", max_length=7, null=True),
        ),
    ]
