# Generated by Django 3.0.8 on 2020-07-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0006_auto_20200707_1214"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberorganisation",
            name="home_club",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberorganisation",
            name="home_state",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
