# Generated by Django 3.0.8 on 2020-08-01 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0008_auto_20200801_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="address1",
            field=models.CharField(
                blank="True", max_length=100, null=True, verbose_name="Address Line 1"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="address2",
            field=models.CharField(
                blank="True", max_length=100, null=True, verbose_name="Address Line 2"
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="bank_account",
            field=models.CharField(
                blank="True",
                max_length=10,
                null=True,
                verbose_name="Bank Account Number",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="bank_bsb",
            field=models.CharField(
                blank="True",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="BSB must be entered in the format: '999-999'.",
                        regex="^\\d{3}-\\d{3}$",
                    )
                ],
                verbose_name="BSB Number",
            ),
        ),
    ]
