# Generated by Django 3.0.8 on 2020-08-01 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0009_auto_20200801_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="bank_account",
            field=models.CharField(
                blank="True",
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Account number must contain only digits and dashes",
                        regex="^[0-9-]*$",
                    )
                ],
                verbose_name="Bank Account Number",
            ),
        ),
    ]
