# Generated by Django 3.2.4 on 2021-08-11 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0013_auto_20210728_0928"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberMembershipType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "home_club",
                    models.BooleanField(
                        default=False, verbose_name="Is Member's Home Club"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Ends At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembershipType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Type of Membership"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Description of Membership Type",
                    ),
                ),
                (
                    "annual_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Annual Fee"
                    ),
                ),
                (
                    "part_year_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Annual Fee",
                    ),
                ),
                (
                    "does_not_pay_session_fees",
                    models.BooleanField(
                        default=False, verbose_name="Does Not Pay Session Fees"
                    ),
                ),
                (
                    "does_not_renew",
                    models.BooleanField(default=False, verbose_name="Does Not Renew"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organisation",
            name="membership_part_year_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Membership Part Year Date"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="membership_renewal_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Membership Renewal Date"
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Closed", "Closed")],
                default="Open",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="secretary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secretary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MemberOrganisation",
        ),
        migrations.AddField(
            model_name="membershiptype",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="membermembershiptype",
            name="membership_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="organisations.membershiptype",
            ),
        ),
    ]
