# Generated by Django 3.2.4 on 2021-08-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0014_auto_20210811_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermembershiptype",
            name="termination_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Cancelled by Member", "Cancelled by Member"),
                    ("Cancelled by Club", "Cancelled by Club"),
                    ("Expired", "Expired"),
                ],
                max_length=20,
                null=True,
                verbose_name="Reason for Membership Termination",
            ),
        ),
    ]
