# Generated by Django 3.2.4 on 2021-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0017_auto_20210813_0619"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membermembershiptype",
            name="member",
        ),
        migrations.AddField(
            model_name="membermembershiptype",
            name="system_number",
            field=models.IntegerField(
                blank=True, default=1, unique=True, verbose_name="ABF Number"
            ),
            preserve_default=False,
        ),
    ]
