# Generated by Django 3.2.4 on 2021-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0018_auto_20210813_2216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermembershiptype",
            name="system_number",
            field=models.IntegerField(blank=True, verbose_name="ABF Number"),
        ),
    ]
