# Generated by Django 3.2.4 on 2021-08-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0019_alter_membermembershiptype_system_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membermembershiptype",
            name="system_number",
        ),
    ]
