# Generated by Django 3.2.4 on 2021-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0020_remove_membermembershiptype_system_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermembershiptype",
            name="system_number",
            field=models.IntegerField(
                blank=True, default=1, unique=True, verbose_name="ABF Number"
            ),
            preserve_default=False,
        ),
    ]
