# Generated by Django 3.2.4 on 2021-08-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0022_alter_membermembershiptype_system_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberClubEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_number", models.IntegerField(verbose_name="ABF Number")),
                ("email", models.EmailField(max_length=254)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
