# Generated by Django 3.2.4 on 2021-08-26 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0023_memberclubemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="membership_part_year_date_month",
            field=models.IntegerField(
                blank=True,
                default=7,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(12),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Membership Part Year Date - Month",
            ),
        ),
    ]
