# Generated by Django 3.2.4 on 2021-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0024_alter_organisation_membership_part_year_date_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberclubemail",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Email for your club only"
            ),
        ),
    ]
