# Generated by Django 3.2.4 on 2021-09-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0026_alter_memberclubemail_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Default Membership Type"
            ),
        ),
    ]
