# Generated by Django 3.2.4 on 2021-09-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0027_membershiptype_is_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershiptype",
            options={"ordering": ("-is_default",)},
        ),
    ]
