# Generated by Django 3.2.4 on 2021-09-06 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0030_alter_organisation_secretary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="secretary",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="secretary",
                to="accounts.user",
            ),
            preserve_default=False,
        ),
    ]
