# Generated by Django 3.2.4 on 2021-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0031_alter_organisation_secretary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberclubtag",
            name="member",
        ),
        migrations.AddField(
            model_name="memberclubtag",
            name="system_number",
            field=models.IntegerField(blank=True, default=0, verbose_name="ABF Number"),
            preserve_default=False,
        ),
    ]
