# Generated by Django 3.2.4 on 2021-09-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0032_auto_20210909_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="org_id",
            field=models.CharField(
                max_length=4, unique=True, verbose_name="ABF Club Number"
            ),
        ),
    ]
