# Generated by Django 3.2.4 on 2021-09-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0033_alter_organisation_org_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationFrontPage",
            fields=[
                (
                    "organisation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="organisations.organisation",
                    ),
                ),
                ("summary", models.TextField()),
            ],
        ),
    ]
