# Generated by Django 3.2.5 on 2021-10-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0035_miscpaytypes_orgvenue"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MiscPayTypes",
            new_name="MiscPayType",
        ),
    ]
