# Generated by Django 3.2.5 on 2021-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0036_rename_miscpaytypes_miscpaytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgvenue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
