# Generated by Django 3.2.12 on 2022-04-08 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0039_alter_organisation_suburb"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgEmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                (
                    "banner",
                    models.ImageField(
                        default="email_banners/default-banner.png",
                        upload_to="email_banners/",
                    ),
                ),
                ("footer", models.TextField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisation",
                    ),
                ),
            ],
        ),
    ]
