# Generated by Django 3.2.12 on 2022-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0042_alter_orgemailtemplate_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgemailtemplate",
            name="from_name",
            field=models.CharField(default="My ABF", max_length=100),
        ),
        migrations.AddField(
            model_name="orgemailtemplate",
            name="reply_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
