# Generated by Django 3.2.12 on 2022-04-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0044_welcomepack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welcomepack",
            name="organisation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.orgemailtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="welcomepack",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="welcome_pack_template",
                to="organisations.orgemailtemplate",
            ),
            preserve_default=False,
        ),
    ]
