# Generated by Django 3.2.12 on 2022-04-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0045_auto_20220416_0849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welcomepack",
            name="organisation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
    ]
