# Generated by Django 3.2.12 on 2022-04-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0046_alter_welcomepack_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welcomepack",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="welcome_pack_template",
                to="organisations.orgemailtemplate",
            ),
        ),
    ]
