# Generated by Django 3.2.10 on 2022-06-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0048_auto_20220416_0935"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="membermembershiptype",
            unique_together={("system_number", "membership_type")},
        ),
    ]
