# Generated by Django 3.2.13 on 2022-06-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0050_alter_membermembershiptype_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermembershiptype",
            name="membership_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.membershiptype",
            ),
        ),
    ]
