# Generated by Django 3.2.13 on 2022-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0051_alter_membermembershiptype_membership_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiptype",
            name="annual_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Annual Fee",
            ),
        ),
    ]
