# Generated by Django 3.2.13 on 2022-06-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0052_alter_membershiptype_annual_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgemailtemplate",
            name="box_colour",
            field=models.CharField(default="#9c27b0", max_length=7),
        ),
        migrations.AddField(
            model_name="orgemailtemplate",
            name="box_font_colour",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="orgemailtemplate",
            name="reply_to",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Reply to"
            ),
        ),
    ]
