# Generated by Django 3.2.13 on 2022-07-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0053_auto_20220620_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="miscpaytype",
            name="default_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
