# Generated by Django 3.2.13 on 2022-07-19 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0069_auto_20220720_0913"),
        ("organisations", "0054_miscpaytype_default_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="default_secondary_payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="org_secondary_payment_type",
                to="payments.orgpaymentmethod",
            ),
        ),
    ]
