# Generated by Django 3.2.14 on 2022-08-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organisations",
            "0056_rename_default_secondary_payment_type_organisation_default_secondary_payment_method",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membermembershiptype",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="membermembershiptype",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="membermembershiptype",
            name="termination_reason",
        ),
        migrations.RemoveField(
            model_name="membermembershiptype",
            name="updated_at",
        ),
    ]
