# Generated by Django 3.2.14 on 2022-08-15 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0057_auto_20220815_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermembershiptype",
            name="start_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Started At",
            ),
            preserve_default=False,
        ),
    ]
