# Generated by Django 3.2.13 on 2022-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0059_organisation_results_email_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="minimum_balance_after_settlement",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
