# Generated by Django 3.2.15 on 2022-10-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0060_organisation_minimum_balance_after_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberclubemail",
            name="email_hard_bounce",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberclubemail",
            name="email_hard_bounce_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberclubemail",
            name="email_hard_bounce_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
