# Generated by Django 3.2.15 on 2023-04-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0063_organisation_xero_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="use_last_payment_method_for_player_sessions",
            field=models.BooleanField(default=False),
        ),
    ]
