# Generated by Django 3.2.19 on 2024-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organisations",
            "0064_organisation_use_last_payment_method_for_player_sessions",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgemailtemplate",
            name="banner",
            field=models.ImageField(
                default="email_banners/myabf-email.png", upload_to="email_banners/"
            ),
        ),
    ]
