# Generated by Django 3.2.19 on 2024-07-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0066_auto_20240722_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberclubdetails",
            name="latest_membership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organisations.membermembershiptype",
            ),
        ),
    ]
