# Generated by Django 3.2.19 on 2024-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0068_clubmemberlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberclubdetails",
            name="previous_membership_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUR", "Current"),
                    ("DUE", "Due"),
                    ("END", "Ended"),
                    ("LAP", "Lapsed"),
                    ("RES", "Resigned"),
                    ("TRM", "Terminated"),
                    ("DEC", "Deceased"),
                    ("CON", "Contact"),
                ],
                default=None,
                max_length=4,
                null=True,
                verbose_name="Provious Membership Status",
            ),
        ),
    ]
