# Generated by Django 3.2.19 on 2024-07-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0069_memberclubdetails_previous_membership_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberclubdetails",
            name="left_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Date Joined"
            ),
        ),
    ]
