# Generated by Django 3.2.19 on 2024-08-10 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0071_alter_memberclubdetails_previous_membership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberclubdetails",
            name="mobile",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="We only accept Australian phone numbers starting 04 which are 10 numbers long.",
                        regex="^04\\d{8}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
    ]
