# Generated by Django 3.2.19 on 2024-08-13 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0072_alter_memberclubdetails_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberclubdetails",
            name="other_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="We only accept Australian phone numbers with 8 or 10 digits.",
                        regex="^(\\d{8}|\\d{10})$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
    ]
