# Generated by Django 3.2.19 on 2024-08-17 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0078_auto_20230614_0728"),
        ("organisations", "0073_alter_memberclubdetails_other_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermembershiptype",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.orgpaymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="memberclubdetails",
            name="membership_status",
            field=models.CharField(
                choices=[
                    ("CUR", "Current"),
                    ("FUT", "Future"),
                    ("DUE", "Due"),
                    ("END", "Ended"),
                    ("LAP", "Lapsed"),
                    ("RES", "Resigned"),
                    ("TRM", "Terminated"),
                    ("DEC", "Deceased"),
                    ("CON", "Contact"),
                ],
                default="CUR",
                max_length=4,
                verbose_name="Membership Status",
            ),
        ),
        migrations.AlterField(
            model_name="memberclubdetails",
            name="previous_membership_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUR", "Current"),
                    ("FUT", "Future"),
                    ("DUE", "Due"),
                    ("END", "Ended"),
                    ("LAP", "Lapsed"),
                    ("RES", "Resigned"),
                    ("TRM", "Terminated"),
                    ("DEC", "Deceased"),
                    ("CON", "Contact"),
                ],
                default=None,
                max_length=4,
                null=True,
                verbose_name="Previous Membership Status",
            ),
        ),
        migrations.AlterField(
            model_name="membermembershiptype",
            name="membership_state",
            field=models.CharField(
                choices=[
                    ("CUR", "Current"),
                    ("FUT", "Future"),
                    ("DUE", "Due"),
                    ("END", "Ended"),
                    ("LAP", "Lapsed"),
                    ("RES", "Resigned"),
                    ("TRM", "Terminated"),
                    ("DEC", "Deceased"),
                ],
                default="CUR",
                max_length=4,
                verbose_name="State",
            ),
        ),
    ]
