# Generated by Django 3.2.19 on 2024-08-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0078_auto_20230614_0728"),
        ("organisations", "0074_auto_20240817_1008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermembershiptype",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payments.orgpaymentmethod",
            ),
        ),
    ]
