# Generated by Django 3.2.19 on 2024-08-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0075_alter_membermembershiptype_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermembershiptype",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Is Paid"),
        ),
    ]
