# Generated by Django 3.2.19 on 2024-08-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0076_membermembershiptype_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermembershiptype",
            name="start_date",
            field=models.DateField(verbose_name="Started At"),
        ),
    ]
