# Generated by Django 3.2.19 on 2024-08-27 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0078_alter_membershiptype_grace_period_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermembershiptype",
            name="auto_pay_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Auto Pay Date"
            ),
        ),
        migrations.AddField(
            model_name="membermembershiptype",
            name="paid_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Paid Date"
            ),
        ),
        migrations.CreateModel(
            name="MemberClubOptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_membership",
                    models.BooleanField(default=True, verbose_name="Allow Membership"),
                ),
                (
                    "allow_auto_pay",
                    models.BooleanField(
                        default=True, verbose_name="Allow Automatic Payment"
                    ),
                ),
                (
                    "share_data",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("ONCE", "Once"),
                            ("ALWAYS", "Always"),
                        ],
                        default="NEVER",
                        max_length=6,
                        verbose_name="Share Data",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisations.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
