# Generated by Django 3.2.19 on 2024-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0079_auto_20240827_1427"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberclubdetails",
            name="mobile",
        ),
        migrations.AddField(
            model_name="memberclubdetails",
            name="preferred_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Preferred Phone"
            ),
        ),
        migrations.AlterField(
            model_name="memberclubdetails",
            name="left_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Date Left"
            ),
        ),
        migrations.AlterField(
            model_name="memberclubdetails",
            name="other_phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
    ]
