# Generated by Django 3.2.19 on 2024-09-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0080_auto_20240909_1350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermembershiptype",
            name="start_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Started At"
            ),
        ),
    ]
