# Generated by Django 3.2.19 on 2024-09-18 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0081_alter_membermembershiptype_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermembershiptype",
            name="fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Fee",
            ),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="annual_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Annual Fee",
            ),
        ),
    ]
