# Generated by Django 3.2.19 on 2024-09-19 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0082_auto_20240918_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiptype",
            name="grace_period_days",
            field=models.IntegerField(
                default=31,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Payment period (days from start of period)",
            ),
        ),
    ]
