# Generated by Django 3.2.19 on 2024-09-25 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0083_alter_membershiptype_grace_period_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiptype",
            name="grace_period_days",
            field=models.IntegerField(
                default=31,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(355),
                ],
                verbose_name="Payment period (days from start of period)",
            ),
        ),
    ]
