# Generated by Django 3.2.19 on 2025-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0086_auto_20240928_0847'),
    ]

    operations = [
        migrations.AddIndex(
            model_name="memberclubdetails",
            index=models.Index(fields=["email"], name="org_mcd_email_idx"),
        ),
        migrations.AddIndex(
            model_name="memberclubdetails",
            index=models.Index(fields=["email_hard_bounce"], name="org_mcd_bounce_idx"),
        ),
        migrations.AddIndex(
            model_name="memberclubdetails",
            index=models.Index(fields=["system_number"], name="org_mcd_sysnum_idx"),
        ),
    ]
