# Generated by Django 2.1 on 2020-03-24 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('DEBUG', 'Level 0 - Debug'), ('INFO', 'Level 1 - Informational'), ('WARN', 'Level 2 - Warning'), ('ERROR', 'Level 3 - Error'), ('HIGH', 'Level 4 - High'), ('CRITICAL', 'Level 5 - Critical')], default='INFO', max_length=8)),
                ('source', models.CharField(max_length=20, null=True)),
                ('sub_source', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
