# Generated by Django 2.1 on 2020-03-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='member',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
