# Generated by Django 2.1 on 2020-03-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200324_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
