# Generated by Django 3.0.9 on 2020-10-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0004_auto_20200502_1048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="source",
            field=models.CharField(blank="True", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="sub_source",
            field=models.CharField(blank="True", max_length=50, null=True),
        ),
    ]
