# Generated by Django 3.0.9 on 2020-12-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_auto_20201013_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="user",
            field=models.CharField(blank="True", max_length=80, null=True),
        ),
    ]
