# Generated by Django 3.0.9 on 2020-12-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0006_auto_20201217_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="message",
            field=models.TextField(blank="True", null=True),
        ),
    ]
