# Generated by Django 3.2.4 on 2021-07-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0007_auto_20201221_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="severity",
            field=models.CharField(
                blank="True",
                choices=[
                    ("DEBUG", "Level 0 - Debug"),
                    ("INFO", "Level 1 - Informational"),
                    ("WARN", "Level 2 - Warning"),
                    ("ERROR", "Level 3 - Error"),
                    ("HIGH", "Level 4 - High"),
                    ("CRITICAL", "Level 5 - Critical"),
                ],
                default="INFO",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="user",
            field=models.CharField(blank="True", max_length=200, null=True),
        ),
    ]
