# Generated by Django 3.0.9 on 2020-08-22 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "run_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Run Date"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="End Time"
                    ),
                ),
                ("instance", models.CharField(max_length=10, verbose_name="Instance")),
                (
                    "node",
                    models.CharField(
                        default="Unknown",
                        max_length=50,
                        verbose_name="Node running job",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("Started", "Job started"),
                            ("Success", "Job completed successfully"),
                            ("Failed", "Job failed to complete"),
                        ],
                        default="Started",
                        max_length=10,
                        verbose_name="Job Status",
                    ),
                ),
            ],
        ),
    ]
