# Generated by Django 3.0.9 on 2020-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_auto_20200822_2227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="instance",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Instance"
            ),
        ),
    ]
