# Generated by Django 3.0.9 on 2020-11-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0003_auto_20200822_2235"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name_plural": "Batches"},
        ),
    ]
