# Generated by Django 3.2.4 on 2021-09-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0005_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lock",
            name="lock_open_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
