# Generated by Django 3.2.10 on 2022-02-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_alter_lock_lock_open_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50)),
                ("redirect_path", models.CharField(max_length=200)),
            ],
        ),
    ]
