# Generated by Django 3.2.10 on 2022-02-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0007_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slug",
            name="slug",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
