# Generated by Django 3.2.15 on 2023-02-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0061_auto_20221014_0533"),
        ("utils", "0008_alter_slug_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="slug",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
            preserve_default=False,
        ),
    ]
