# Generated by Django 2.1.5 on 2020-03-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestIt',
        ),
    ]
