# Generated by Django 2.2.12 on 2020-05-23 01:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='InAppNotification',
        ),
    ]
