# Generated by Django 2.2.12 on 2020-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200528_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmapping',
            name='event_type',
            field=models.CharField(default='unset', max_length=50, verbose_name='Event Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationmapping',
            name='application',
            field=models.CharField(choices=[('Forums', 'Forums'), ('Payments', 'Payments')], max_length=20, verbose_name='Application'),
        ),
    ]
