# Generated by Django 3.0.9 on 2020-10-31 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_auto_20200528_1522"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[("Queued", "Queued to Send"), ("Sent", "Sent")],
                        default="Queued",
                        max_length=6,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Create Date"
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sent Date"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "abstractemail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.AbstractEmail",
                    ),
                ),
            ],
            bases=("notifications.abstractemail",),
        ),
        migrations.CreateModel(
            name="EmailArchive",
            fields=[
                (
                    "abstractemail_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.AbstractEmail",
                    ),
                ),
            ],
            bases=("notifications.abstractemail",),
        ),
    ]
