# Generated by Django 3.0.9 on 2020-10-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_abstractemail_email_emailarchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractemail",
            name="recipient",
            field=models.CharField(
                default="", max_length=50, verbose_name="Recipients"
            ),
            preserve_default=False,
        ),
    ]
