# Generated by Django 3.0.9 on 2020-10-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_auto_20201031_1827"),
    ]

    operations = [
        migrations.RemoveField(model_name="abstractemail", name="actor",),
    ]
