# Generated by Django 3.2.4 on 2021-07-18 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0012_auto_20210607_1336"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractemail",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
