# Generated by Django 3.2.4 on 2021-08-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0011_models_help_text"),
        ("notifications", "0013_abstractemail_sender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snooper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ses_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Sent At"),
                ),
                (
                    "ses_delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "ses_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Opened At"
                    ),
                ),
                (
                    "ses_clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clicked At"
                    ),
                ),
                (
                    "post_office_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post_office.email",
                    ),
                ),
            ],
        ),
    ]
