# Generated by Django 3.2.4 on 2021-08-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0014_snooper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snooper",
            name="ses_clicked_at",
        ),
        migrations.RemoveField(
            model_name="snooper",
            name="ses_opened_at",
        ),
        migrations.AddField(
            model_name="snooper",
            name="ses_clicked_count",
            field=models.IntegerField(default=0, verbose_name="Clicked Count"),
        ),
        migrations.AddField(
            model_name="snooper",
            name="ses_last_clicked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Clicked At"
            ),
        ),
        migrations.AddField(
            model_name="snooper",
            name="ses_last_opened_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Opened At"
            ),
        ),
        migrations.AddField(
            model_name="snooper",
            name="ses_open_count",
            field=models.IntegerField(default=0, verbose_name="Open Count"),
        ),
    ]
