# Generated by Django 3.2.4 on 2021-08-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "0011_models_help_text"),
        ("notifications", "0015_auto_20210819_2205"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snooper",
            name="id",
        ),
        migrations.AlterField(
            model_name="snooper",
            name="post_office_email",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="post_office.email",
            ),
        ),
    ]
