# Generated by Django 3.2.4 on 2021-08-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0016_auto_20210823_0630"),
    ]

    operations = [
        migrations.AddField(
            model_name="snooper",
            name="ses_bounce_reason",
            field=models.TextField(blank=True, null=True, verbose_name="Bounce Reason"),
        ),
        migrations.AddField(
            model_name="snooper",
            name="ses_last_bounce_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Bounce At"
            ),
        ),
    ]
