# Generated by Django 3.2.4 on 2021-09-18 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0033_alter_organisation_org_id"),
        ("notifications", "0018_auto_20210911_1254"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchid",
            name="meta_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisations.organisation",
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="meta_sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
