# Generated by Django 3.2.5 on 2021-10-29 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0020_auto_20210918_1151"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        choices=[
                            ("CE", "Convener Email By Event"),
                            ("CO", "Convener Email By Org"),
                        ],
                        max_length=2,
                    ),
                ),
                ("app", models.CharField(choices=[("EV", "Events")], max_length=2)),
                ("model_id", models.IntegerField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
