# Generated by Django 3.2.5 on 2021-10-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0021_blocknotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blocknotification",
            name="app",
        ),
    ]
