# Generated by Django 3.2.10 on 2021-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0023_realtimenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimenotification",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
