# Generated by Django 3.2.10 on 2021-12-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0025_auto_20211215_0829"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="send_status",
            field=models.BooleanField(default=False),
        ),
    ]
