# Generated by Django 3.2.10 on 2021-12-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0027_realtimenotificationheader_successful_send_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="invalid_records_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="total_record_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="uncontactable_users",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="unregistered_users",
            field=models.TextField(blank=True, null=True),
        ),
    ]
