# Generated by Django 3.2.10 on 2021-12-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0029_auto_20211218_1737"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtimenotificationheader",
            name="invalid_records_number",
        ),
    ]
