# Generated by Django 3.2.10 on 2021-12-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0030_remove_realtimenotificationheader_invalid_records_number",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimenotification",
            name="aws_message_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
