# Generated by Django 3.2.10 on 2022-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0031_realtimenotification_aws_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimenotification',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
    ]
