# Generated by Django 3.2.15 on 2022-10-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_alter_unregistereduser_identifier"),
        ("notifications", "0034_alter_emailattachment_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnregisteredBlockedEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "un_registered_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.unregistereduser",
                    ),
                ),
            ],
        ),
    ]
