# Generated by Django 3.2.15 on 2023-01-23 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fcm_django", "0009_alter_fcmdevice_user"),
        ("notifications", "0035_unregisteredblockedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimenotification",
            name="fcm_device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="fcm_django.fcmdevice",
            ),
        ),
    ]
