# Generated by Django 3.2.15 on 2023-03-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0036_realtimenotification_fcm_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimenotificationheader",
            name="sender_identification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
