# Generated by Django 3.2.19 on 2024-03-10 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "organisations",
            "0064_organisation_use_last_payment_method_for_player_sessions",
        ),
        ("notifications", "0038_snooper_limited_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("S", "Series"), ("C", "Congress"), ("E", "Event")],
                        max_length=1,
                        verbose_name="Activity Type",
                    ),
                ),
                ("activity_id", models.IntegerField(verbose_name="Activity Id")),
            ],
        ),
        migrations.AddField(
            model_name="batchid",
            name="batch_size",
            field=models.IntegerField(default=0, verbose_name="Batch Size"),
        ),
        migrations.AddField(
            model_name="batchid",
            name="batch_type",
            field=models.CharField(
                choices=[
                    ("ADM", "Admin"),
                    ("COM", "Comms"),
                    ("CNG", "Congress"),
                    ("EVT", "Event"),
                    ("MBR", "Member"),
                    ("MLT", "Multi"),
                    ("RES", "Results"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=3,
                verbose_name="Batch Type",
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="complete",
            field=models.BooleanField(default=False, verbose_name="Complete"),
        ),
        migrations.AddField(
            model_name="batchid",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Created Date"
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="description",
            field=models.CharField(
                blank=True,
                default="New batch",
                max_length=989,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="organisations.organisation",
            ),
        ),
    ]
