# Generated by Django 3.2.19 on 2024-03-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0039_auto_20240310_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchactivity",
            name="batch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="notifications.batchid",
            ),
            preserve_default=False,
        ),
    ]
