# Generated by Django 3.2.19 on 2024-03-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0041_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="include",
            field=models.BooleanField(default=True, verbose_name="Include"),
        ),
    ]
