# Generated by Django 3.2.19 on 2024-03-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0043_recipient_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="system_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="ABF Number"),
        ),
    ]
