# Generated by Django 3.2.19 on 2024-03-24 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organisations",
            "0064_organisation_use_last_payment_method_for_player_sessions",
        ),
        ("notifications", "0044_auto_20240313_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchid",
            name="from_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="From Name"
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="reply_to",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Reply To"
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="organisations.orgemailtemplate",
            ),
        ),
    ]
