# Generated by Django 3.2.19 on 2024-03-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0046_batchattachment_batchcontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchid",
            name="complete",
        ),
        migrations.AddField(
            model_name="batchid",
            name="state",
            field=models.CharField(
                choices=[
                    ("WIP", "In progress"),
                    ("INF", "Being Sent"),
                    ("CMP", "Complete"),
                ],
                default="WIP",
                max_length=3,
                verbose_name="State",
            ),
        ),
    ]
