# Generated by Django 3.2.19 on 2024-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0048_alter_recipient_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchid",
            name="batch_type",
            field=models.CharField(
                choices=[
                    ("ADM", "Admin"),
                    ("COM", "Comms"),
                    ("CNG", "Congress"),
                    ("EVT", "Event"),
                    ("MBR", "Member"),
                    ("MLT", "Multi"),
                    ("RES", "Results"),
                    ("ENT", "Entry"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=3,
                verbose_name="Batch Type",
            ),
        ),
        migrations.AlterField(
            model_name="batchid",
            name="description",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=989,
                null=True,
                verbose_name="Description",
            ),
        ),
    ]
