# Generated by Django 3.2.19 on 2024-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0049_auto_20240409_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchid",
            name="state",
            field=models.CharField(
                choices=[
                    ("WIP", "In progress"),
                    ("INF", "Being Sent"),
                    ("ERR", "Errored"),
                    ("CMP", "Complete"),
                ],
                default="WIP",
                max_length=3,
                verbose_name="State",
            ),
        ),
    ]
