# Generated by Django 3.2.19 on 2024-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0050_alter_batchid_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchid",
            name="batch_type",
            field=models.CharField(
                choices=[
                    ("ADM", "Admin"),
                    ("COM", "Comms"),
                    ("CNG", "Congress"),
                    ("EVT", "Event"),
                    ("MBR", "Member"),
                    ("MLT", "Multi-event"),
                    ("RES", "Results"),
                    ("ENT", "Entry"),
                    ("UNK", "Unknown"),
                ],
                default="UNK",
                max_length=3,
                verbose_name="Batch Type",
            ),
        ),
    ]
