# Generated by Django 3.2.19 on 2024-05-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0051_alter_batchid_batch_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchid",
            name="date_range_from",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="From Date"
            ),
        ),
        migrations.AddField(
            model_name="batchid",
            name="date_range_to",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="To Date"
            ),
        ),
    ]
